### ISSUE TITLE
Subtype error when generating docs for fake_package

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#154]
Currently, in our code we do this:

```
(element.node as AnnotatedNode).documentationComment.references;
```

Which generates this error:

```
parsing /Users/sethladd/Code/dartdoc/test/fake_package/lib/example.dart...
parsing /Users/sethladd/Code/dartdoc/test/fake_package/lib/fake.dart...
generating docs/new/index.html
Unhandled exception:
type 'SimpleIdentifier' is not a subtype of type 'AnnotatedNode' in type cast.
#0      ModelElement.documentation (package:dartdoc/src/model.dart:85:25)
#1      ModelElement.docOneLiner (package:dartdoc/src/model.dart:369:15)
#2      Eval.<anonymous closure> (:1:16)
```

**Comment by sethladd** [comment]
Bug report invalid. We do need to upgr

**Comment by sethladd** [comment]
To repro:

cd test/fake_package
dart ../../bin/dartdoc.dart

**Comment by keertip** [comment]
ok, will take a took.

**Comment by sethladd** [comment]
Ah, in the docs for Element:

```
   *
   * @return the resolved [AstNode], maybe `null` if [Element] is synthetic or
   *         isn't contained in a compilation unit, such as a [LibraryElement].
   */
  AstNode get node;
```

The code fails when we encounter LibraryElement, which now makes sense. :)

**Comment by sethladd** [comment]
Hm, maybe this is a bug in analyzer? `node` is returning an instance of `SimpleIdentifier`... maybe it should return null?

**Comment by sethladd** [comment]
Sorry, I'm having a hard time working around this. Kind of blocked.

**Comment by sethladd** [comment]
yay, thanks!
