### ISSUE TITLE
dartdoc's flutter travis shard is broken

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/dartdoc#1596]
Related to [flutter/flutter#14601](https://github.com/flutter/flutter/pull/14061).  @Hixie mentions the new version code requires tags, which don't work with git clone --depth 1 (used on our bots).

```
--snip--
Precompiled dartdoc:dartdoc.
Installed executable dartdoc.
Activated dartdoc 0.15.1.
Resolving dependencies... 
Overriding the upper bound Dart SDK constraint to <=2.0.0-dev.16.0 for the following packages:

archive, args, async, charcode, collection, convert, crypto, http, http_parser, intl, path, source_span, string_scanner

To disable this you can set the PUB_ALLOW_PRERELEASE_SDK system environment variable to `false`, or you can silence this message by setting it to `quiet`.
Got dependencies!
pub:stdout: Resolving dependencies...
pub:stderr: Error on line 3, column 10 of pubspec.yaml: Invalid version number: Could not parse "unknown".
pub:stderr: version: unknown
pub:stderr:          ^^^^^^^
```

**Comment by jcollins-g** [comment]
There is apparently another problem:

```
build-flutter-docs: Got dependencies!
build-flutter-docs: Package dartdoc is currently active at path "/home/travis/build/dart-lang/dartdoc".
build-flutter-docs: Installed executable dartdoc.
build-flutter-docs: Activated dartdoc 0.15.1 at path "/home/travis/build/dart-lang/dartdoc".
build-flutter-docs: + (cd "/tmp/flutterGEZRSB" && /tmp/flutterGEZRSB/bin/cache/dart-sdk/bin/dart dev/tools/dartdoc.dart)
build-flutter-docs: Unhandled exception:
build-flutter-docs: ProcessException: No such file or directory
build-flutter-docs:   Command: flutter
build-flutter-docs: #0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:473)
build-flutter-docs: #1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:619)
build-flutter-docs: #2      Process.runSync (dart:io-patch/process_patch.dart:66)
build-flutter-docs: #3      main (file:///tmp/flutterGEZRSB/dev/tools/dartdoc.dart:38:41)
build-flutter-docs: <asynchronous suspension>
build-flutter-docs: #4      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
build-flutter-docs: #5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)
ProcessException: SubprocessLauncher got non-zero exitCode
  Command: /tmp/flutterGEZRSB/bin/cache/dart-sdk/bin/dart dev/tools/dartdoc.dart
#0      SubprocessLauncher.runStreamed (package:dartdoc/src/io_utils.dart:165:7)
<asynchronous suspension>
```
