### ISSUE TITLE
Library-level docs with links throw exception

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#168]
Consider this case:

```
/// # WOW FAKE PACKAGE IS __BEST__ [PACKAGE][pkg]
///
/// If you don't have this package yet, get it.
/// Don't ask questions.
///
/// *Why should you get this package?*
///
/// * We told you so.
/// * Everyone is doing it.
/// * It smells nice.
///
/// [pkg]: http://example.org
library fake;
```

throws this error:

```
generating docs/new/index.html
Unhandled exception:
The null object does not have a method 'firstWhere'.

NoSuchMethodError: method not found: 'firstWhere'
Receiver: null
Arguments: [Closure: (dynamic) => dynamic]
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#1      ModelElement._processRefs (package:dartdoc/src/model.dart:109:48)
#2      ModelElement.documentation (package:dartdoc/src/model.dart:90:36)
#3      ModelElement.docOneLiner (package:dartdoc/src/model.dart:406:15)
#4      Eval.<anonymous closure> (:1:16)
#5      _LocalInstanceMirror._getFieldSlow.<anonymous closure> (dart:mirrors-patch/mirrors_impl.dart:469)
#6      _LocalInstanceMirror.getField (dart:mirrors-patch/mirrors_impl.dart:477)
#7      _ObjectReflectorDeclaration.value (package:mustache4dart/mustache_context.dart:245:27)
#8      _ObjectReflector.[] (package:mustache4dart/mustache_context.dart:199:24)
#9      _MustacheContext._getActualValue (package:mustache4dart/mustache_context.dart:110:56)
#10     _MustacheContext._getMustachContext (package:mustache4dart/mustache_context.dart:87:28)
#11     _MustacheContext._getContextForKey (package:mustache4dart/mustache_context.dart:83:30)
#12     _MustacheContext._getInThisOrParent (package:mustache4dart/mustache_context.dart:56:35)
```

**Comment by sethladd** [comment]
Looking into more, not sure our current strategy is going to work.

A string like `/// # WOW FAKE PACKAGE IS __BEST__ [PACKAGE][pkg]` is first parsed as "comment refs" so the analyzer thinks `[pkg]` is a comment ref.

Unfortunately, we have two ways to specify a link, and they are both so similar in syntax.

**Comment by sethladd** [comment]
I worked around this... but we'll need to refactor and create a new issue.
