### ISSUE TITLE
Dartdoc runs in travis are occasionally dying without providing debugging output

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/dartdoc#1770]
I'm still seeing occasional flakes and crashes of dartdoc with no visible traceback in our Travis, and therefore no way to debug them. Tests of the process output helpers in io_utils.dart (e.g. runStreamed) suggest that a subprocess that is terminated by signal (e.g. SIGKILL) may not always have their buffers flushed, and this prevents us getting the crucial information about what the process might have been doing right before it died.

Force enable line-buffering in subprocesses to fix this problem.

**Comment by jcollins-g** [comment]
Example of travis run with non-useful output (from https://travis-ci.org/dart-lang/dartdoc/jobs/435773563)

```
flutter-docs:   warning: unresolved doc reference [n], from vector_math_64.Vector2.clamp: (file:///tmp/pubcacheTTXDCL/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/vector2.dart:347:8)
flutter-docs:   warning: unresolved doc reference [n], from vector_math_64.Vector3.clamp: (file:///tmp/pubcacheTTXDCL/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/vector3.dart:478:8)
flutter-docs:   warning: unresolved doc reference [n], from vector_math_64.Vector4.clamp: (file:///tmp/pubcacheTTXDCL/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/vector4.dart:373:8)
flutter-docs: Generating docs for library vector_math_geometry from package:vector_math/vector_math_geometry.dart...
flutter-docs: Generating docs for library vector_math_lists from package:vector_math/vector_math_lists.dart...
flutter-docs:   warning: unresolved doc reference [vectorLength], from vector_math_lists.ScalarListView: (file:///tmp/pubcacheTTXDCL/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_lists/scalar_list_view.dart:29:3)
flutter-docs:   warning: unresolved doc reference [vectorLength], from vector_math_lists.ScalarListView.fromList: (file:///tmp/pubcacheTTXDCL/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_lists/scalar_list_view.dart:38:18)
flutter-docs: Generating docs for library vector_math_operations from package:vector_math/vector_math_operations.dart...
flutter-docs: Generating docs for library web_socket_channel from package:web_socket_channel/web_socket_channel.dart...
flutter-docs: Generating docs for library web_socket_channel.io from package:web_socket_channel/io.dart...
flutter-docs:   warning: web_socket_channel.io has no library level documentation comments, from web_socket_channel.io: (file:///tmp/pubcacheTTXDCL/hosted/pub.dartlang.org/web_socket_channel-1.0.9/lib/io.dart:5:9)
flutter-docs: Generating docs for library web_socket_channel.status from package:web_socket_channel/status.dart...
ProcessException: SubprocessLauncher got non-zero exitCode
  Command: /tmp/flutterNKZVLT/bin/cache/dart-sdk/bin/dart dev/tools/dartdoc.dart -c --json
#0      SubprocessLauncher.runStreamed (package:dartdoc/src/io_utils.dart:199:7)
<asynchronous suspension>
#1      _buildFlutterDocs (file:///home/travis/build/dart-lang/dartdoc/tool/grind.dart:616:37)
<asynchronous suspension>
#2      buildFlutterDocs (file:///home/travis/build/dart-lang/dartdoc/tool/grind.dart:532:9)
<asynchronous suspension>
#3      _LocalLibraryMirror._invoke (dart:mirrors/runtime/libmirrors_impl.dart:1104:36)
#4      _LocalObjectMirror.invoke (dart:mirrors/runtime/libmirrors_impl.dart:230:25)
#5      TaskDiscovery.discoverDeclaration.<anon> (package:grinder/src/discover_tasks.dart:79:38)
#6      _rootRun (dart:async/zone.dart:1124:13)
#7      _CustomZone.run (dart:async/zone.dart:1021:19)
#8      _runZoned (dart:async/zone.dart:1516:10)
#9      runZoned (dart:async/zone.dart:1463:12)
#10     ZonedValue.withValue (package:grinder/src/utils.dart:112:12)
#11     GrinderTask.execute (package:grinder/src/grinder_task.dart:64:27)
#12     Grinder._invokeTask (package:grinder/src/grinder.dart:193:27)
#13     Grinder.start.<anon> (package:grinder/src/grinder.dart:168:16)
#14     Future.forEach.<anon> (dart:async/future.dart:491:26)
#15     Future.doWhile.<anon> (dart:async/future.dart:533:26)
#16     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#17     _RootZone.bindUnaryCallbackGuarded.<anon> (dart:async/zone.dart:1353:26)
#18     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#22     Future._complete (dart:async/future_impl.dart:476:7)
#23     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#24     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#25     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#26     testDartdocFlutterPlugin (file:///home/travis/build/dart-lang/dartdoc/tool/grind.dart)
<asynchronous suspension>
#27     _LocalLibraryMirror._invoke (dart:mirrors/runtime/libmirrors_impl.dart:1104:36)
#28     _LocalObjectMirror.invoke (dart:mirrors/runtime/libmirrors_impl.dart:230:25)
#29     TaskDiscovery.discoverDeclaration.<anon> (package:grinder/src/discover_tasks.dart:79:38)
#30     _rootRun (dart:async/zone.dart:1124:13)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _runZoned (dart:async/zone.dart:1516:10)
#33     runZoned (dart:async/zone.dart:1463:12)
#34     ZonedValue.withValue (package:grinder/src/utils.dart:112:12)
#35     GrinderTask.execute (package:grinder/src/grinder_task.dart:64:27)
#36     Grinder._invokeTask (package:grinder/src/grinder.dart:193:27)
#37     Grinder.start.<anon> (package:grinder/src/grinder.dart:168:16)
#38     Future.forEach.<anon> (dart:async/future.dart:491:26)
#39     Future.doWhile.<anon> (dart:async/future.dart:533:26)
#40     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#41     _RootZone.bindUnaryCallbackGuarded.<anon> (dart:async/zone.dart:1353:26)
#42     Future.doWhile (dart:async/future.dart:548:18)
#43     Future.forEach (dart:async/future.dart:489:12)
#44     Grinder.start (package:grinder/src/grinder.dart:167:21)
#45     runTasks (package:grinder/src/cli.dart:67:39)
<asynchronous suspension>
#46     grind (package:grinder/grinder.dart:46:12)
#47     main (file:///home/travis/build/dart-lang/dartdoc/tool/grind.dart:16:35)
The command "./tool/travis.sh" exited with 1.
cache.2
store build cache
0.00s
73.20schange detected (content changed, file is created, or file is deleted):
/home/travis/.dartdoc_grinder/cleanFlutter/bin/cache/artifacts/engine/android-arm64-dynamic-profile/flutter.jar
/home/travis/.dartdoc_grinder/cleanFlutter/bin/cache/artifacts/engine/android-arm64-dynamic-profile/linux-x64/gen_snapshot
/home/travis/.dartdoc_grinder/cleanFlutter/bin/cache/artifacts/engine/android-arm64-dynamic-release/flutter.jar
/home/travis/.dartdoc_grinder/cleanFlutter/bin/cache/artifacts/engine/android-arm64-dynamic-release/linux-x64/gen_snapshot
/home/travis/.dartdoc_grinder/cleanFlutter/bin/cache/artifacts/engine/android-arm64/flutter.jar
/home/travis/.dartdoc_grinder/cleanFlutter/bin/cache/artifacts/engine/android-arm64-profile/flutter.jar
/home/travis/.dartdoc_grinder/cleanFlutter/bin/cache/artifacts/engine/android-arm64-profile/linux-x64/gen_snapshot
/home/travis/.dartdoc_grinder/cleanFlutter/bin/cache/artifacts/engine/android-arm64-release/flutter.jar
/home/travis/.dartdoc_grinder/cleanFlutter/bin/cache/artifacts/engine/android-arm64-release/linux-x64/gen_snapsh
...
changes detected, packing new archive
.
.
.
.
.
.
.
.
.
uploading archive
Done. Your build exited with 1.
```

**Comment by jcollins-g** [comment]
First try with just enabling line buffering didn't help.  Going to try core dumps next.

**Comment by jcollins-g** [comment]
#1799 was discovered as a result of #1788 and other work to fix this.
