### ISSUE TITLE
assert firing in macro resolution in flutter on bots

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/dartdoc#1810]
Assert fired on flutter.dart:ui.boxHeightStyle.includeLineSpacing for attempting to add a macro once Dartdoc believes the macro index has already been built.

This might cause a macro to fail to be resolved sometimes in flutter, a non fatal (but ugly) error for those pages.

```
flutter-docs:   warning: unresolved doc reference [Snackbar]
flutter-docs:     from dart-ui.SemanticsAction.dismiss: (file:///tmp/flutterBHVGJQ/bin/cache/pkg/sky_engine/lib/ui/semantics.dart:166:32)
flutter-docs:     in documentation inherited from dart-ui.SemanticsAction.dismiss: (file:///tmp/flutterBHVGJQ/bin/cache/pkg/sky_engine/lib/ui/semantics.dart:166:32)
flutter-docs:   warning: unresolved doc reference [accessibilityFlags]
flutter-docs:     from dart-ui.Window.onAccessibilityFeaturesChanged: (file:///tmp/flutterBHVGJQ/bin/cache/pkg/sky_engine/lib/ui/window.dart)
flutter-docs:     in documentation inherited from dart-ui.Window.onAccessibilityFeaturesChanged: (file:///tmp/flutterBHVGJQ/bin/cache/pkg/sky_engine/lib/ui/window.dart:697:20)
flutter-docs:   warning: undefined macro [flutter.dart:ui.boxHeightStyle.includeLineSpacing], from dart-ui.BoxHeightStyle.includeLineSpacingBottom: (file:///tmp/flutterBHVGJQ/bin/cache/pkg/sky_engine/lib/ui/text.dart:993:5)
flutter-docs:
flutter-docs: Generation failed: 'package:dartdoc/src/model.dart': Failed assertion: line 5372 pos 12: '!_localDocumentationBuilt': is not true.
flutter-docs: dart:core                                                                                                       _AssertionError._throwNew
flutter-docs: package:dartdoc/src/model.dart 5372:12                                                                          PackageGraph._addMacro
flutter-docs: package:dartdoc/src/model.dart 4238:20                                                                          ModelElement._stripMacroTemplatesAndAddToIndex.<fn>
flutter-docs: dart:core                                                                                                       _StringBase.replaceAllMapped
flutter-docs: package:dartdoc/src/model.dart 4237:20                                                                          ModelElement._stripMacroTemplatesAndAddToIndex
flutter-docs: package:dartdoc/src/model.dart 3231:18                                                                          ModelElement._buildDocumentationBase
flutter-docs: package:dartdoc/src/model.dart 3217:40                                                                          ModelElement._buildDocumentationLocal
flutter-docs: package:dartdoc/src/model.dart 3243:31                                                                          ModelElement.documentationLocal
flutter-docs: package:dartdoc/src/model.dart 3249:40                                                                          ModelElement.documentation.<fn>
flutter-docs: dart:_internal                                                                                                  ListIterable.join
flutter-docs: package:dartdoc/src/model.dart 3249:60                                                                          ModelElement.documentation
flutter-docs: package:dartdoc/src/model.dart 1891:45                                                                          _Field&ModelElement&GetterSetterCombo.documentationFrom.<fn>
flutter-docs: dart:collection                                                                                                 _ListBase&Object&ListMixin.every
flutter-docs: package:dartdoc/src/model.dart 1891:30                                                                          _Field&ModelElement&GetterSetterCombo.documentationFrom
flutter-docs: package:dartdoc/src/model.dart 1580:18                                                                          EnumField.documentationFrom
flutter-docs: package:dartdoc/src/model.dart 1672:5                                                                           Field.documentation
flutter-docs: package:dartdoc/src/model.dart 1590:20                                                                          EnumField.documentation
flutter-docs: package:dartdoc/src/markdown_processor.dart 898:28                                                              Documentation._renderMarkdownToHtml
flutter-docs: package:dartdoc/src/markdown_processor.dart 875:9                                                               Documentation._renderHtmlForDartdoc
flutter-docs: package:dartdoc/src/markdown_processor.dart 857:7                                                               Documentation.asHtml
flutter-docs: package:dartdoc/src/model.dart 3382:62                                                                          ModelElement.documentationAsHtml
flutter-docs: package:dartdoc/src/model.dart 1622:28                                                                          EnumField.oneLineDoc
flutter-docs: dart:mirrors                                                                                                    _LocalInstanceMirror.getField
flutter-docs: package:dartdoc/src/third_party/pkg/mustache4dart/lib/src/mirrors.dart 111:35                                   _MethodMirrorField.val
flutter-docs: package:dartdoc/src/third_party/pkg/mustache4dart/lib/mustache_context.dart 122:45                              _MustacheContext._getMustacheContext
flutter-docs: package:dartdoc/src/third_party/pkg/mustache4dart/lib/mustache_context.dart 118:12                              _MustacheContext._getContextForKey
flutter-docs: package:dartdoc/src/third_party/pkg/mustache4dart/lib/mustache_context.dart 82:18                               _MustacheContext._getInThisOrParent
flutter-docs: package:dartdoc/src/third_party/pkg/mustache4dart/lib/mustache_context.dart 78:12                               _MustacheContext.field
flutter-docs: /usr/local/google/home/jcollins/dart/dartdoc/lib/src/third_party/pkg/mustache4dart/lib/src/tokens.dart 169:21   _ExpressionToken.apply
flutter-docs: /usr/local/google/home/jcollins/dart/dartdoc/lib/src/third_party/pkg/mustache4dart/lib/src/tokens.dart 40:18    Token.call
flutter-docs: /usr/local/google/home/jcollins/dart/dartdoc/lib/src/third_party/pkg/mustache4dart/lib/src/tmpl.dart 101:20     _Template._write
flutter-docs: /usr/local/google/home/jcollins/dart/dartdoc/lib/src/third_party/pkg/mustache4dart/lib/src/tmpl.dart 76:5       _Template.call
flutter-docs: /usr/local/google/home/jcollins/dart/dartdoc/lib/src/third_party/pkg/mustache4dart/lib/src/mustache.dart 11:64  render
flutter-docs: /usr/local/google/home/jcollins/dart/dartdoc/lib/src/third_party/pkg/mustache4dart/lib/src/tokens.dart 211:16   _PartialToken.apply
flutter-docs: /usr/local/google/home/jcollins/dart/dartdoc/lib/src/third_party/pkg/mustache4dart/lib/src/tokens.dart 286:57   _StartSectionToken.apply.<fn>.<fn>
flutter-docs: /usr/local/google/home/jcollins/dart/dartdoc/lib/src/third_party/pkg/mustache4dart/lib/src/tokens.dart 309:8    _StartSectionToken.forEachUntilEndSection
flutter-docs: /usr/local/google/home/jcollins/dart/dartdoc/lib/src/third_party/pkg/mustache4dart/lib/src/tokens.dart 286:9    _StartSectionToken.apply.<fn>
flutter-docs: dart:core                                                                                                       Iterable.forEach
flutter-docs: /usr/local/google/home/jcollins/dart/dartdoc/lib/src/third_party/pkg/mustache4dart/lib/src/tokens.dart 285:27   _StartSectionToken.apply
flutter-docs: /usr/local/google/home/jcollins/dart/dartdoc/lib/src/third_party/pkg/mustache4dart/lib/src/tokens.dart 299:53   _StartSectionToken.apply.<fn>
flutter-docs: /usr/local/google/home/jcollins/dart/dartdoc/lib/src/third_party/pkg/mustache4dart/lib/src/tokens.dart 309:8    _StartSectionToken.forEachUntilEndSection
flutter-docs: /usr/local/google/home/jcollins/dart/dartdoc/lib/src/third_party/pkg/mustache4dart/lib/src/tokens.dart 299:5    _StartSectionToken.apply
flutter-docs: /usr/local/google/home/jcollins/dart/dartdoc/lib/src/third_party/pkg/mustache4dart/lib/src/tokens.dart 40:18    Token.call
flutter-docs: /usr/local/google/home/jcollins/dart/dartdoc/lib/src/third_party/pkg/mustache4dart/lib/src/tmpl.dart 101:20     _Template._write
flutter-docs: /usr/local/google/home/jcollins/dart/dartdoc/lib/src/third_party/pkg/mustache4dart/lib/src/tmpl.dart 76:5       _Template.call
flutter-docs: package:dartdoc/src/html/html_generator_instance.dart 381:30                                                    HtmlGeneratorInstance._build
flutter-docs: package:dartdoc/src/html/html_generator_instance.dart 299:5                                                     HtmlGeneratorInstance.generateEnum
flutter-docs: package:dartdoc/src/html/html_generator_instance.dart 211:11                                                    HtmlGeneratorInstance._generateDocs
flutter-docs: package:dartdoc/src/html/html_generator_instance.dart 36:7                                                      HtmlGeneratorInstance.generate
flutter-docs: ===== asynchronous gap ===========================
flutter-docs: dart:async                                                                                                      _AsyncAwaitCompleter.completeError
flutter-docs: package:dartdoc/src/html/html_generator_instance.dart                                                           HtmlGeneratorInstance.generate
flutter-docs: ===== asynchronous gap ===========================
flutter-docs: dart:async                                                                                                      _asyncThenWrapperHelper
flutter-docs: package:dartdoc/dartdoc.dart                                                                                    Dartdoc.generateDocsBase
flutter-docs: package:dartdoc/dartdoc.dart 177:43                                                                             Dartdoc.generateDocs
flutter-docs:

ProcessException: SubprocessLauncher got non-zero exitCode: 255
  Command: /tmp/flutterBHVGJQ/bin/cache/dart-sdk/bin/dart dev/tools/dartdoc.dart -c --json
#0      SubprocessLauncher.runStreamed (package:dartdoc/src/io_utils.dart:214:7)
<asynchronous suspension>
#1      _buildFlutterDocs (file:///usr/local/google/home/jcollins/dart/dartdoc/tool/grind.dart:684:37)
<asynchronous suspension>
#2      buildFlutterDocs (file:///usr/local/google/home/jcollins/dart/dartdoc/tool/grind.dart:595:9)
<asynchronous suspension>
#3      _LocalLibraryMirror._invoke (dart:mirrors/runtime/libmirrors_impl.dart:1104:36)
#4      _LocalObjectMirror.invoke (dart:mirrors/runtime/libmirrors_impl.dart:230:25)
#5      TaskDiscovery.discoverDeclaration.<anon> (package:grinder/src/discover_tasks.dart:79:38)
#6      _rootRun (dart:async/zone.dart:1124:13)
#7      _CustomZone.run (dart:async/zone.dart:1021:19)
#8      _runZoned (dart:async/zone.dart:1516:10)
#9      runZoned (dart:async/zone.dart:1463:12)
#10     ZonedValue.withValue (package:grinder/src/utils.dart:112:12)
#11     GrinderTask.execute (package:grinder/src/grinder_task.dart:64:27)
#12     Grinder._invokeTask (package:grinder/src/grinder.dart:193:27)
#13     Grinder.start.<anon> (package:grinder/src/grinder.dart:168:16)
#14     Future.forEach.<anon> (dart:async/future.dart:491:26)
#15     Future.doWhile.<anon> (dart:async/future.dart:533:26)
#16     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#17     _RootZone.bindUnaryCallbackGuarded.<anon> (dart:async/zone.dart:1353:26)
#18     Future.doWhile (dart:async/future.dart:548:18)
#19     Future.forEach (dart:async/future.dart:489:12)
#20     Grinder.start (package:grinder/src/grinder.dart:167:21)
#21     runTasks (package:grinder/src/cli.dart:67:39)
<asynchronous suspension>
#22     grind (package:grinder/grinder.dart:46:12)
#23     main (file:///usr/local/google/home/jcollins/dart/dartdoc/tool/grind.dart:16:35)
```

**Comment by jcollins-g** [comment]
Looks like we are not including accessors that are part of constants in our initial trawl through dartdoc structures to populate the macro index -- thereby hitting this assert later on when we stumble into a template definition that is part of a constant accessor now in dart:ui for flutter.
