### ISSUE TITLE
Unhandled exception while generating doc for flutter_plugin_tools/0.0.14+1

### ISSUE THREAD

**Issue by isoos** [dart-lang/dartdoc#1833]
dartdoc version: 0.24.1
full log: https://pub.dartlang.org/documentation/flutter_plugin_tools/latest/log.txt

````
Unhandled exception:
Bad state: No element
#0      List.first (dart:core/runtime/libgrowable_array.dart:215:5)
#1      Package.isFirstPackage (package:dartdoc/src/model.dart:5930:67)
#2      Package.isDocumented (package:dartdoc/src/model.dart:5791:7)
#3      PackageGraph._warnOnElement (package:dartdoc/src/model.dart:4811:19)
#4      PackageGraph.warnOnElement (package:dartdoc/src/model.dart:4776:5)
#5      Package.warn (package:dartdoc/src/model.dart:5950:18)
#6      _showWarningsForGenericsOutsideSquareBracketsBlocks.<anonymous closure> (package:dartdoc/src/markdown_processor.dart:698:15)
#7      List.forEach (dart:core/runtime/libgrowable_array.dart:278:8)
#8      _showWarningsForGenericsOutsideSquareBracketsBlocks (package:dartdoc/src/markdown_processor.dart:689:18)
#9      Documentation._renderMarkdownToHtml (package:dartdoc/src/markdown_processor.dart:899:5)
#10     Documentation._renderHtmlForDartdoc (package:dartdoc/src/markdown_processor.dart:875:9)
#11     Documentation.asHtml (package:dartdoc/src/markdown_processor.dart:857:7)
#12     Package.documentationAsHtml (package:dartdoc/src/model.dart:5763:63)
````

**Comment by jcollins-g** [comment]
This package has no documentable libraries, which Dartdoc is not prepared for.  We should do a better job of handling this gracefully.

**Comment by isoos** [comment]
SGTM
