### ISSUE TITLE
Unhandled exception while generating doc for kernel 0.3.6+4

### ISSUE THREAD

**Issue by isoos** [dart-lang/dartdoc#1834]
dartdoc version: 0.24.1
full log: https://pub.dartlang.org/documentation/kernel/latest/log.txt

````
type 'DynamicElementImpl' is not a subtype of type 'ClassElement' in type cast
#0      ModelElement.annotationsFromMetadata (package:dartdoc/src/model.dart:3045:22)
#1      ModelElement.annotations (package:dartdoc/src/model.dart:3031:35)
#2      Field.annotations (package:dartdoc/src/model.dart:1723:34)
#3      ModelElement._baseFeatures (package:dartdoc/src/model.dart:3139:24)
#4      Field.features (package:dartdoc/src/model.dart:1735:31)
#5      ModelElement.featuresAsString (package:dartdoc/src/model.dart:3157:32)
#6      _LocalInstanceMirror._invokeGetter (dart:mirrors/runtime/libmirrors_impl.dart:329:76)
#7      _LocalInstanceMirror.getField (dart:mirrors/runtime/libmirrors_impl.dart:296:20)
#8      _MethodMirrorField.val (package:dartdoc/src/third_party/pkg/mustache4dart/lib/src/mirrors.dart:111:35)
#9      _MustacheContext._getMustacheContext (package:dartdoc/src/third_party/pkg/mustache4dart/lib/mustache_context.dart:122:45)
#10     _MustacheContext._getContextForKey (package:dartdoc/src/third_party/pkg/mustache4dart/lib/mustache_context.dart:110:19)
#11     _MustacheContext._getInThisOrParent (package:dartdoc/src/third_party/pkg/mustache4dart/lib/mustache_context.dart:82:18)
#12     _MustacheContext.field (package:dartdoc/src/third_party/pkg/mustache4dart/lib/mustache_context.dart:78:12)
#13     _StartSectionToken.apply (file:///root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.24.1/lib/src/third_party/pkg/mustache4dart/lib/src/tokens.dart:275:21)
#14     Token.call (file:///root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.24.1/lib/src/third_party/pkg/mustache4dart/lib/src/tokens.dart:40:18)
#15     _Template._write (file:///root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.24.1/lib/src/third_party/pkg/mustache4dart/lib/src/tmpl.dart:101:20)
#16     _Template.call (file:///root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.24.1/lib/src/third_party/pkg/mustache4dart/lib/src/tmpl.dart:76:5)
#17     render (file:///root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.24.1/lib/src/third_party/pkg/mustache4dart/lib/src/mustache.dart:11:64)
#18     _PartialToken.apply (file:///root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.24.1/lib/src/third_party/pkg/mustache4dart/lib/src/tokens.dart:211:16)
#19     Token.call (file:///root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.24.1/lib/src/third_party/pkg/mustache4dart/lib/src/tokens.dart:40:18)
#20     _Template._write (file:///root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.24.1/lib/src/third_party/pkg/mustache4dart/lib/src/tmpl.dart:101:20)
#21     _Template.call (file:///root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.24.1/lib/src/third_party/pkg/mustache4dart/lib/src/tmpl.dart:76:5)
#22     render (file:///root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.24.1/lib/src/third_party/pkg/mustache4dart/lib/src/mustache.dart:11:64)
#23     _PartialToken.apply (file:///root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.24.1/lib/src/third_party/pkg/mustache4dart/lib/src/tokens.dart:211:16)
#24     _StartSectionToken.apply.<anonymous closure>.<anonymous closure> (file:///root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.24.1/lib/src/third_party/pkg/mustache4dart/lib/src/tokens.dart:286:57)
#25     _StartSectionToken.forEachUntilEndSection (file:///root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.24.1/lib/src/third_party/pkg/mustache4dart/lib/src/tokens.dart:309:8)
#26     _StartSectionToken.apply.<anonymous closure> (file:///root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.24.1/lib/src/third_party/pkg/mustache4dart/lib/src/tokens.dart:286:9)
#27     Iterable.forEach (dart:core/iterable.dart:277:30)
#28     _StartSectionToken.apply (file:///root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.24.1/lib/src/third_party/pkg/mustache4dart/lib/src/tokens.dart:285:27)
#29     _StartSectionToken.apply.<anonymous closure> (file:///root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.24.1/lib/src/third_party/pkg/mustache4dart/lib/src/tokens.dart:299:53)
#30     _StartSectionToken.forEachUntilEndSection (file:///root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.24.1/lib/src/third_party/pkg/mustache4dart/lib/src/tokens.dart:309:8)
#31     _StartSectionToken.apply (file:///root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.24.1/lib/src/third_party/pkg/mustache4dart/lib/src/tokens.dart:299:5)
#32     Token.call (file:///root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.24.1/lib/src/third_party/pkg/mustache4dart/lib/src/tokens.dart:40:18)
#33     _Template._write (file:///root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.24.1/lib/src/third_party/pkg/mustache4dart/lib/src/tmpl.dart:101:20)
#34     _Template.call (file:///root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.24.1/lib/src/third_party/pkg/mustache4dart/lib/src/tmpl.dart:76:5)
#35     HtmlGeneratorInstance._build (package:dartdoc/src/html/html_generator_instance.dart:381:30)
#36     HtmlGeneratorInstance.generateClass (package:dartdoc/src/html/html_generator_instance.dart:276:5)
#37     HtmlGeneratorInstance._generateDocs (package:dartdoc/src/html/html_generator_instance.dart:134:11)
#38     HtmlGeneratorInstance.generate (package:dartdoc/src/html/html_generator_instance.dart:36:7)
<asynchronous suspension>
#39     HtmlGenerator.generate (package:dartdoc/src/html/html_generator.dart:107:23)
<asynchronous suspension>
#40     Dartdoc.generateDocsBase (package:dartdoc/dartdoc.dart:153:25)
<asynchronous suspension>
#41     Dartdoc.generateDocs (package:dartdoc/dartdoc.dart:177:43)
<asynchronous suspension>
#42     main (file:///project/pkg/pub_dartdoc/bin/pub_dartdoc.dart:27:17)
<asynchronous suspension>
#43     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#44     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
````

**Comment by devoncarew** [comment]
@jcollins-g, we may want to extend the dartdoc travis bots to generate package docs for the top n packages on pub.

**Comment by jcollins-g** [comment]
@devoncarew the packages bot already runs one package (angular), but can and should be extended to others that prove problematic or are important.  I'll do that as part of this work.

**Comment by jcollins-g** [comment]
I don't understand how dartdoc got as far as it did in the log, but this package is damaged -- it has paths that can't resolve in its dev_dependencies.

**Comment by isoos** [comment]
We remove `dev_dependencies` and run `pub upgrade` without it.
