### ISSUE TITLE
Unhandled exception while generating doc for access 1.0.1+2

### ISSUE THREAD

**Issue by isoos** [dart-lang/dartdoc#1835]
dartdoc: 0.24.1
full log: https://pub.dartlang.org/documentation/access/latest/log.txt

````
NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      ModelElement._buildFullyQualifiedName (package:dartdoc/src/model.dart:3798:55)
#2      ModelElement._buildFullyQualifiedName (package:dartdoc/src/model.dart:3798:12)
#3      ModelElement.fullyQualifiedName (package:dartdoc/src/model.dart:3414:37)
#4      _findRefElementInLibrary.<anonymous closure> (package:dartdoc/src/markdown_processor.dart:524:30)
#5      __CompactLinkedHashSet&_HashFieldBase&_HashBase&_OperatorEqualsAndHashCode&SetMixin.any (dart:collection/set.dart:198:15)
#6      _findRefElementInLibrary (package:dartdoc/src/markdown_processor.dart:524:17)
#7      _getMatchingLinkElement (package:dartdoc/src/markdown_processor.dart:202:9)
#8      _linkDocReference (package:dartdoc/src/markdown_processor.dart:650:12)
#9      Documentation._renderMarkdownToHtml._linkResolver (package:dartdoc/src/markdown_processor.dart:895:26)
#10     LinkSyntax._resolveReferenceLink (package:markdown/src/inline_parser.dart:699:14)
#11     LinkSyntax._tryAddReferenceLink (package:markdown/src/inline_parser.dart:721:9)
#12     LinkSyntax.onMatchEnd (package:markdown/src/inline_parser.dart:671:12)
#13     TagState.close (package:markdown/src/inline_parser.dart:1191:16)
#14     TagState.tryMatch (package:markdown/src/inline_parser.dart:1130:7)
#15     InlineParser.parse.<anonymous closure> (package:markdown/src/inline_parser.dart:104:57)
#16     ListIterable.any (dart:_internal/iterable.dart:89:15)
#17     InlineParser.parse (package:markdown/src/inline_parser.dart:104:12)
#18     MarkdownDocument._parseInlineContent (package:dartdoc/src/markdown_processor.dart:795:57)
#19     MarkdownDocument._parseInlineContent (package:dartdoc/src/markdown_processor.dart:800:9)
#20     MarkdownDocument.renderLinesToHtml (package:dartdoc/src/markdown_processor.dart:820:5)
#21     Documentation._renderMarkdownToHtml (package:dartdoc/src/markdown_processor.dart:905:21)
#22     Documentation._renderHtmlForDartdoc (package:dartdoc/src/markdown_processor.dart:875:9)
#23     Documentation.asOneLiner (package:dartdoc/src/markdown_processor.dart:866:7)
#24     ModelElement.computeOneLineDoc (package:dartdoc/src/model.dart:3562:25)
#25     ModelElement.oneLineDoc (package:dartdoc/src/model.dart:3567:21)
#26     _LocalInstanceMirror._invokeGetter (dart:mirrors/runtime/libmirrors_impl.dart:329:76)
#27     _LocalInstanceMirror.getField (dart:mirrors/runtime/libmirrors_impl.dart:296:20)
#28     _MethodMirrorField.val (package:dartdoc/src/third_party/pkg/mustache4dart/lib/src/mirrors.dart:111:35)
#29     _MustacheContext._getMustacheContext (package:dartdoc/src/third_party/pkg/mustache4dart/lib/mustache_context.dart:122:45)
#30     _MustacheContext._getContextForKey (package:dartdoc/src/third_party/pkg/mustache4dart/lib/mustache_context.dart:118:12)
#31     _MustacheContext._getInThisOrParent (package:dartdoc/src/third_party/pkg/mustache4dart/lib/mustache_context.dart:82:18)
#32     _MustacheContext.field (package:dartdoc/src/third_party/pkg/mustache4dart/lib/mustache_context.dart:78:12)
#33     _ExpressionToken.apply (file:///root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.24.1/lib/src/third_party/pkg/mustache4dart/lib/src/tokens.dart:169:21)
#34     Token.call (file:///root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.24.1/lib/src/third_party/pkg/mustache4dart/lib/src/tokens.dart:40:18)
#35     _Template._write (file:///root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.24.1/lib/src/third_party/pkg/mustache4dart/lib/src/tmpl.dart:101:20)
#36     _Template.call (file:///root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.24.1/lib/src/third_party/pkg/mustache4dart/lib/src/tmpl.dart:76:5)
#37     render (file:///root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.24.1/lib/src/third_party/pkg/mustache4dart/lib/src/mustache.dart:11:64)
#38     _PartialToken.apply (file:///root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.24.1/lib/src/third_party/pkg/mustache4dart/lib/src/tokens.dart:211:16)
#39     _StartSectionToken.apply.<anonymous closure>.<anonymous closure> (file:///root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.24.1/lib/src/third_party/pkg/mustache4dart/lib/src/tokens.dart:286:57)
#40     _StartSectionToken.forEachUntilEndSection (file:///root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.24.1/lib/src/third_party/pkg/mustache4dart/lib/src/tokens.dart:309:8)
#41     _StartSectionToken.apply.<anonymous closure> (file:///root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.24.1/lib/src/third_party/pkg/mustache4dart/lib/src/tokens.dart:286:9)
#42     Iterable.forEach (dart:core/iterable.dart:277:30)
#43     _StartSectionToken.apply (file:///root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.24.1/lib/src/third_party/pkg/mustache4dart/lib/src/tokens.dart:285:27)
#44     _StartSectionToken.apply.<anonymous closure> (file:///root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.24.1/lib/src/third_party/pkg/mustache4dart/lib/src/tokens.dart:299:53)
#45     _StartSectionToken.forEachUntilEndSection (file:///root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.24.1/lib/src/third_party/pkg/mustache4dart/lib/src/tokens.dart:309:8)
#46     _StartSectionToken.apply (file:///root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.24.1/lib/src/third_party/pkg/mustache4dart/lib/src/tokens.dart:299:5)
#47     Token.call (file:///root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.24.1/lib/src/third_party/pkg/mustache4dart/lib/src/tokens.dart:40:18)
#48     _Template._write (file:///root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.24.1/lib/src/third_party/pkg/mustache4dart/lib/src/tmpl.dart:101:20)
#49     _Template.call (file:///root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.24.1/lib/src/third_party/pkg/mustache4dart/lib/src/tmpl.dart:76:5)
#50     HtmlGeneratorInstance._build (package:dartdoc/src/html/html_generator_instance.dart:381:30)
#51     HtmlGeneratorInstance.generateLibrary (package:dartdoc/src/html/html_generator_instance.dart:269:5)
#52     HtmlGeneratorInstance._generateDocs (package:dartdoc/src/html/html_generator_instance.dart:131:9)
#53     HtmlGeneratorInstance.generate (package:dartdoc/src/html/html_generator_instance.dart:36:7)
<asynchronous suspension>
#54     HtmlGenerator.generate (package:dartdoc/src/html/html_generator.dart:107:23)
<asynchronous suspension>
#55     Dartdoc.generateDocsBase (package:dartdoc/dartdoc.dart:153:25)
<asynchronous suspension>
#56     Dartdoc.generateDocs (package:dartdoc/dartdoc.dart:177:43)
<asynchronous suspension>
#57     main (file:///project/pkg/pub_dartdoc/bin/pub_dartdoc.dart:27:17)
<asynchronous suspension>
#58     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#59     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
````

**Comment by jcollins-g** [comment]
Having some trouble calculating names for parameters of anonymous function definitions inside parameter lists.
