### ISSUE TITLE
Use `allowMalformed: true` with utf8.decode when checking for `hasDocumentation`

### ISSUE THREAD

**Issue by isoos** [dart-lang/dartdoc#1889]
Otherwise with a few bad UTF-8 characters it will throw:
````
FileSystemException: Failed to decode data using encoding 'utf-8', path = '/tmp/pub-dartlang-dartdocNPAPOD/pkg/README.md'
#0      _File._tryDecode (dart:io/file_impl.dart:576:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:596:7)
#2      FileContents.contents (package:dartdoc/src/package_meta.dart:215:31)
#3      Package.hasDocumentation (package:dartdoc/src/model.dart:5990:54)
#4      _LocalInstanceMirror._invokeGetter (dart:mirrors/runtime/libmirrors_impl.dart:329:76)
````

**Comment by jcollins-g** [comment]
P1 (Uncaught exceptions, very rare or with simple workarounds)

**Comment by isoos** [comment]
`sudoku 0.1.2` for one, I need to look if you need a more up-to-date package. #1890 looks good to me.

**Comment by jcollins-g** [comment]
No worries.  sudoku has about what I expected in its README.  I think #1890 should work for it, once that package becomes Dart 2 compatible.
