### ISSUE TITLE
dartdoc crashes on invalid prefix imports

### ISSUE THREAD

**Issue by isoos** [dart-lang/dartdoc#1896]
NPE on vint 0.7.3 (dartdoc 0.27.0)

Generating docs for `vint 0.7.3`:
````
Unhandled exception:
NoSuchMethodError: The getter 'kind' was called on null.
Receiver: null
Tried calling: kind
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      new ModelElement.from (package:dartdoc/src/model.dart:2913:11)
#2      Library.prefixToLibrary (package:dartdoc/src/model.dart:2242:19)
#3      _MarkdownCommentReference._findReferenceFromPrefixes (package:dartdoc/src/markdown_processor.dart:570:51)
#4      _MarkdownCommentReference.computeReferredElement (package:dartdoc/src/markdown_processor.dart:383:17)
#5      _getMatchingLinkElement (package:dartdoc/src/markdown_processor.dart:202:10)
#6      _linkDocReference (package:dartdoc/src/markdown_processor.dart:743:12)
#7      Documentation._renderMarkdownToHtml._linkResolver (package:dartdoc/src/markdown_processor.dart:988:26)
#8      LinkSyntax._resolveReferenceLink (package:markdown/src/inline_parser.dart:699:14)
#9      LinkSyntax._tryAddReferenceLink (package:markdown/src/inline_parser.dart:721:9)
````

**Comment by jcollins-g** [comment]
This package is extremely broken on Dart 2.0+  The specific problem is that there is a prefix import 'dart:json' that doesn't resolve, and the new prefix support assumed that the dart code to document was valid.
