### ISSUE TITLE
dartdoc will crash if a package references dart libraries that do not end in '.dart'

### ISSUE THREAD

**Issue by isoos** [dart-lang/dartdoc#1897]
NPE on trello_dart 0.0.1 (dartdoc 0.27.0)

Exception while generating doc for `trello_dart 0.0.1`:

````
NoSuchMethodError: The getter 'inheritanceManager' was called on null.
Receiver: null
Tried calling: inheritanceManager
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      Class._inheritedElements (package:dartdoc/src/model.dart:1044:61)
#2      Class.inheritedMethods (package:dartdoc/src/model.dart:836:11)
#3      Class.allInstanceMethods (package:dartdoc/src/model.dart:626:48)
#4      Class.allModelElements (package:dartdoc/src/model.dart:730:13)
#5      Library.modelElementsMap.<anonymous closure> (package:dartdoc/src/model.dart:2614:15)
#6      ExpandIterator.moveNext (dart:_internal/iterable.dart:481:29)
#7      ExpandIterator.moveNext (dart:_internal/iterable.dart:475:31)
#8      Iterable.forEach (dart:core/iterable.dart)
#9      Library.modelElementsMap (package:dartdoc/src/model.dart:2631:15)
#10     Library.allModelElements (package:dartdoc/src/model.dart:2645:47)
````

**Comment by jcollins-g** [comment]
trello_dart does something technically valid but unexpected: it has dart files that don't have the correct suffix.
