### ISSUE TITLE
dartdoc throws exception attempting to find offset inside empty file

### ISSUE THREAD

**Issue by isoos** [dart-lang/dartdoc#1938]
We've found it while running `dartdoc` on `native_widgets 1.0.0+4`.

````
Unhandled exception:
RangeError (start): Invalid value: Only valid value is 0: 1
#0      _StringBase.indexOf (dart:core/runtime/libstring_patch.dart:334:7)
#1      String.indexOf (dart:core/runtime/libstring_patch.dart:1024:18)
#2      _createLineNumbersMap (package:dartdoc/src/line_number_cache.dart:30:23)
#3      LineNumberCache.lineAndColumn.<anonymous closure> (package:dartdoc/src/line_number_cache.dart:47:21)
#4      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:281:23)
#5      LineNumberCache.lineAndColumn (package:dartdoc/src/line_number_cache.dart:46:32)
#6      ModelElement.lineAndColumn (package:dartdoc/src/model.dart:3499:40)
#7      new SourceLinker.fromElement (package:dartdoc/src/source_linker.dart:88:27)
#8      ModelElement.sourceHref (package:dartdoc/src/model.dart:3222:25)
````

**Comment by jcollins-g** [comment]
the referenced package contains a file, lib/scaffold/ios_controllers/navigation_controller.dart, of zero length.

It is valid to have a dart library of zero length, but dartdoc doesn't handle this case appropriately.
