### ISSUE TITLE
Unhandled exception: Unknown type NeverElementImpl

### ISSUE THREAD

**Issue by isoos** [dart-lang/dartdoc#2023]
```
Dart SDK: 2.5.0
dartdoc: 0.28.5
```

Pub site running `dartdoc` on `package:analyzer 0.38.2` throws the following exception: [see log.txt](https://pub.dev/documentation/analyzer/latest/log.txt)

```
Unhandled exception:
Unknown type NeverElementImpl
#0      new ModelElement.from (package:dartdoc/src/model.dart:3084:34)
#1      new ModelElement.fromElement (package:dartdoc/src/model.dart:2929:25)
#2      _MarkdownCommentReference._findAnalyzerReferences (package:dartdoc/src/markdown_processor.dart:682:51)
#3      _MarkdownCommentReference.computeReferredElement (package:dartdoc/src/markdown_processor.dart:392:17)
#4      _getMatchingLinkElement (package:dartdoc/src/markdown_processor.dart:210:14)
#5      _linkDocReference (package:dartdoc/src/markdown_processor.dart:758:12)
#6      Documentation._renderMarkdownToHtml._linkResolver (package:dartdoc/src/markdown_processor.dart:1006:22)
#7      LinkSyntax._resolveReferenceLink (package:markdown/src/inline_parser.dart:698:14)
#8      LinkSyntax._tryAddReferenceLink (package:markdown/src/inline_parser.dart:720:9)
#9      LinkSyntax.onMatchEnd (package:markdown/src/inline_parser.dart:670:12)
#10     TagState.close (package:markdown/src/inline_parser.dart:1194:16)
#11     TagState.tryMatch (package:markdown/src/inline_parser.dart:1133:7)
#12     InlineParser.parse.<anonymous closure> (package:markdown/src/inline_parser.dart:104:57)
#13     ListIterable.any (dart:_internal/iterable.dart:89:15)
#14     InlineParser.parse (package:markdown/src/inline_parser.dart:104:12)
#15     MarkdownDocument._parseInlineContent (package:dartdoc/src/markdown_processor.dart:903:53)
#16     MarkdownDocument._parseInlineContent (package:dartdoc/src/markdown_processor.dart:908:9)
#17     MarkdownDocument.renderLinesToHtml (package:dartdoc/src/markdown_processor.dart:928:5)
#18     Documentation._renderMarkdownToHtml (package:dartdoc/src/markdown_processor.dart:1016:21)
#19     Documentation._renderHtmlForDartdoc (package:dartdoc/src/markdown_processor.dart:986:9)
#20     Documentation.asOneLiner (package:dartdoc/src/markdown_processor.dart:977:7)
#21     ModelElement.computeOneLineDoc (package:dartdoc/src/model.dart:3697:25)
#22     _Field&ModelElement&GetterSetterCombo.oneLineDoc (package:dartdoc/src/model.dart:1997:23)
#23     _LocalInstanceMirror._invokeGetter (dart:mirrors-patch/mirrors_impl.dart:329:76)
#24     _LocalInstanceMirror.getField (dart:mirrors-patch/mirrors_impl.dart:296:20)
#25     Renderer._getNamedProperty (package:mustache/src/renderer.dart:245:29)
#26     Renderer.resolveValue (package:mustache/src/renderer.dart:212:16)
#27     Renderer.visitVariable (package:mustache/src/renderer.dart:90:17)
```

**Comment by devoncarew** [comment]
Note, we're seeing this for the analyzer docs on pub: https://github.com/dart-lang/pub-dev/issues/2762

**Comment by keertip** [comment]
Was able to reproduce. Fixed is in the analyzer documentation, landed in https://github.com/dart-lang/sdk/commit/329091236627ab380fc866685c49e5a6eecf9aa8.

**Comment by isoos** [comment]
I think bad documentation can happen in other packages too, and if it happens, it should not be able to trigger an Exception in `dartdoc`. (this also affects our ability to generate docs for `analyzer` versions that do not and will not have the documentation block fixed)

**Comment by keertip** [comment]
There needs to be a release of the analyzer with the doc fix to get the pub site doc gen working again.

**Comment by stereotype441** [comment]
New analyzer published (0.38.4)

**Comment by isoos** [comment]
Thanks!

**Comment by jcollins-g** [comment]
@isoos / @keertip / @stereotype441   Is the issue resolved now?

**Comment by keertip** [comment]
Yes, pub is back to generating docs for the analyzer.
