### ISSUE TITLE
flutter throws assert for duplicate files now

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/dartdoc#2110]
Sometime in the last 24 hours, a change at flutter head results in dartdoc failing an assert for generating duplicate files.

**Comment by jcollins-g** [comment]
```
flutter-docs: Generating docs for library webdriver.core from package:webdriver/core.dart...
flutter-docs: Generating docs for library webdriver.core from package:webdriver/async_core.dart...
flutter-docs:
flutter-docs: dartdoc failed: 'package:dartdoc/src/html/html_generator.dart': Failed assertion: line 93 pos 14: 'allowOverwrite || !writtenFiles.contains(filePath)': is not true.
flutter-docs: dart:core                                                    _AssertionError._throwNew
flutter-docs: package:dartdoc/src/html/html_generator.dart 93:14           HtmlGenerator.generate.write
flutter-docs: package:dartdoc/src/html/html_generator_instance.dart 416:5  HtmlGeneratorInstance._build
flutter-docs: package:dartdoc/src/html/html_generator_instance.dart 304:5  HtmlGeneratorInstance.generateLibrary
flutter-docs: package:dartdoc/src/html/html_generator_instance.dart 135:9  HtmlGeneratorInstance._generateDocs
flutter-docs: package:dartdoc/src/html/html_generator_instance.dart 39:7   HtmlGeneratorInstance.generate
flutter-docs: package:dartdoc/src/html/html_generator.dart 116:23          HtmlGenerator.generate
flutter-docs: package:dartdoc/dartdoc.dart 107:25                          Dartdoc.generateDocsBase
flutter-docs: ===== asynchronous gap ===========================
flutter-docs: package:dartdoc/dartdoc.dart 134:43                          Dartdoc.generateDocs
flutter-docs: dart:async                                                   runZoned
flutter-docs: /home/travis/build/dart-lang/dartdoc/bin/dartdoc.dart 96:13  main.<fn>
flutter-docs: package:stack_trace                                          Chain.capture
flutter-docs: /home/travis/build/dart-lang/dartdoc/bin/dartdoc.dart 95:17  main
flutter-docs:
ProcessException: SubprocessLauncher got non-zero exitCode: 255
  Command: /tmp/flutterTEZQDU/bin/cache/dart-sdk/bin/dart dev/tools/dartdoc.dart -c --json
#0      SubprocessLauncher.runStreamed (file:///home/travis/build/dart-lang/dartdoc/test/src/utils.dart:368:7)
<asynchronous suspension>
#1      _buildFlutterDocs (file:///home/travis/build/dart-lang/dartdoc/tool/grind.dart:739:37)
<asynchronous suspension>
#2      buildFlutterDocs (file:///home/travis/build/dart-lang/dartdoc/tool/grind.dart:647:9)
#3      _LibraryMirror._invoke (dart:mirrors-patch/mirrors_impl.dart:1082:36)
#4      _ObjectMirror.invoke (dart:mirrors-patch/mirrors_impl.dart:232:25)
#5      TaskDiscovery.discoverDeclaration.<anon> (package:grinder/src/discover_tasks.dart:79:38)
#6      _rootRun (dart:async/zone.dart:1126:13)
#7      _CustomZone.run (dart:async/zone.dart:1023:19)
#8      _runZoned (dart:async/zone.dart:1518:10)
```

**Comment by jcollins-g** [comment]
Dartdoc believes there are two libraries named webdriver.core and webdriver.io.

**Comment by jcollins-g** [comment]
The webdriver package has explicitly named two separate library files with the same name in both instances, leading to this issue.  It's one of those cases that is hard to handle cleanly given our assumptions in the file naming scheme.
