### ISSUE TITLE
travis failure fetching angular

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/dartdoc#2234]
```
build-angular->=5.1.0: + (cd "/tmp/pubcacheACSUCS/hosted/pub.dartlang.org/angular-5.3.1" && PUB_CACHE=/tmp/pubcacheACSUCS PATH=/tmp/pubcacheACSUCS/bin:/home/travis/.rvm/gems/ruby-2.5.3/bin:/home/travis/.rvm/gems/ruby-2.5.3@global/bin:/home/travis/.rvm/rubies/ruby-2.5.3/bin:/home/travis/.rvm/bin:/home/travis/.pub-cache/bin:/home/travis/dart-sdk/bin:/home/travis/bin:/home/travis/.local/bin:/usr/local/lib/jvm/openjdk11/bin:/opt/pyenv/shims:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v8.12.0/bin:/home/travis/.kiex/elixirs/elixir-1.7.4/bin:/home/travis/.kiex/bin:/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.11.1.linux.amd64/bin:/usr/local/cmake-3.12.4/bin:/usr/local/clang-7.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/opt/ghc/bin:/home/travis/.phpenv/bin:/opt/pyenv/bin:/home/travis/.yarn/bin:~/.pub-cache/bin pub get)
build-angular->=5.1.0: Resolving dependencies...
build-angular->=5.1.0: + analyzer 0.35.4 (0.39.10 available)
build-angular->=5.1.0: + angular_ast 0.5.9 (0.5.11 available)
build-angular->=5.1.0: + angular_compiler 0.4.3 (0.4.5 available)
build-angular->=5.1.0: + args 1.6.0
build-angular->=5.1.0: + async 2.4.1
build-angular->=5.1.0: + build 1.3.0
build-angular->=5.1.0: + build_config 0.4.2
build-angular->=5.1.0: + built_collection 4.3.2
build-angular->=5.1.0: + built_value 7.1.0
build-angular->=5.1.0: + charcode 1.1.3
build-angular->=5.1.0: + checked_yaml 1.0.2
build-angular->=5.1.0: + code_builder 3.3.0
build-angular->=5.1.0: + collection 1.14.12
build-angular->=5.1.0: + convert 2.1.1
build-angular->=5.1.0: + crypto 2.1.5
build-angular->=5.1.0: + csslib 0.14.6+1 (0.16.1 available)
build-angular->=5.1.0: + dart_style 1.2.4 (1.3.6 available)
build-angular->=5.1.0: + fixnum 0.10.11
build-angular->=5.1.0: + front_end 0.1.14 (0.1.29 available)
build-angular->=5.1.0: + glob 1.2.0
build-angular->=5.1.0: + intl 0.15.8 (0.16.1 available)
build-angular->=5.1.0: + js 0.6.2
build-angular->=5.1.0: + json_annotation 3.0.1
build-angular->=5.1.0: + kernel 0.3.14 (0.3.29 available)
build-angular->=5.1.0: + logging 0.11.4
build-angular->=5.1.0: + matcher 0.12.6
build-angular->=5.1.0: + meta 1.1.8
build-angular->=5.1.0: + node_interop 1.1.1
build-angular->=5.1.0: + node_io 1.1.1
build-angular->=5.1.0: + package_config 1.9.3
build-angular->=5.1.0: + path 1.7.0
build-angular->=5.1.0: + pedantic 1.9.0
build-angular->=5.1.0: + pub_semver 1.4.4
build-angular->=5.1.0: + pubspec_parse 0.1.5
build-angular->=5.1.0: + quiver 2.1.3
build-angular->=5.1.0: + source_gen 0.9.4+4 (0.9.5 available)
build-angular->=5.1.0: + source_span 1.7.0
build-angular->=5.1.0: + stack_trace 1.9.3
build-angular->=5.1.0: + string_scanner 1.0.5
build-angular->=5.1.0: + term_glyph 1.1.0
build-angular->=5.1.0: + typed_data 1.1.6
build-angular->=5.1.0: + watcher 0.9.7+15
build-angular->=5.1.0: + yaml 2.2.1
build-angular->=5.1.0: Downloading angular_compiler 0.4.3...
build-angular->=5.1.0: Downloading angular_ast 0.5.9...
build-angular->=5.1.0: Downloading csslib 0.14.6+1...
build-angular->=5.1.0: Downloading stack_trace 1.9.3...
build-angular->=5.1.0: Downloading meta 1.1.8...
build-angular->=5.1.0: Downloading logging 0.11.4...
build-angular->=5.1.0: Downloading js 0.6.2...
build-angular->=5.1.0: Downloading charcode 1.1.3...
build-angular->=5.1.0: Downloading path 1.7.0...
build-angular->=5.1.0: Downloading analyzer 0.35.4...
build-angular->=5.1.0: Downloading kernel 0.3.14...
build-angular->=5.1.0: Downloading front_end 0.1.14...
build-angular->=5.1.0: Downloading pub_semver 1.4.4...
build-angular->=5.1.0: Downloading convert 2.1.1...
build-angular->=5.1.0: Downloading string_scanner 1.0.5...
build-angular->=5.1.0: Downloading collection 1.14.12...
build-angular->=5.1.0: Downloading yaml 2.2.1...
build-angular->=5.1.0: Downloading typed_data 1.1.6...
build-angular->=5.1.0: Downloading args 1.6.0...
build-angular->=5.1.0: Downloading source_span 1.7.0...
build-angular->=5.1.0: Downloading term_glyph 1.1.0...
build-angular->=5.1.0: Downloading code_builder 3.3.0...
build-angular->=5.1.0: Downloading package_config 1.9.3...
build-angular->=5.1.0: Downloading built_value 7.1.0...
build-angular->=5.1.0: Downloading fixnum 0.10.11...
build-angular->=5.1.0: Downloading build 1.3.0...
build-angular->=5.1.0: Downloading glob 1.2.0...
build-angular->=5.1.0: Downloading node_io 1.1.1...
build-angular->=5.1.0: Downloading node_interop 1.1.1...
build-angular->=5.1.0: Downloading pedantic 1.9.0...
build-angular->=5.1.0: Downloading intl 0.15.8...
build-angular->=5.1.0: Downloading crypto 2.1.5...
build-angular->=5.1.0: Downloading build_config 0.4.2...
build-angular->=5.1.0: Downloading pubspec_parse 0.1.5...
build-angular->=5.1.0: Downloading checked_yaml 1.0.2...
build-angular->=5.1.0: Downloading json_annotation 3.0.1...
build-angular->=5.1.0: Downloading watcher 0.9.7+15...
build-angular->=5.1.0: Downloading async 2.4.1...
build-angular->=5.1.0: Downloading source_gen 0.9.4+4...
build-angular->=5.1.0: Downloading matcher 0.12.6...
build-angular->=5.1.0: Downloading built_collection 4.3.2...
build-angular->=5.1.0: Downloading dart_style 1.2.4...
build-angular->=5.1.0: Downloading quiver 2.1.3...
build-angular->=5.1.0: Cannot open file, path = '/tmp/pubcacheACSUCS/global_packages/angular/pubspec.lock' (OS Error: No such file or directory, errno = 2)
ProcessException: SubprocessLauncher got non-zero exitCode: 66
  Command: pub get
#0      SubprocessLauncher.runStreamed (file:///home/travis/build/dart-lang/dartdoc/test/src/utils.dart:387:7)
<asynchronous suspension>
#1      _buildPubPackageDocs (file:///home/travis/build/dart-lang/dartdoc/tool/grind.dart:824:20)
<asynchronous suspension>
#2      buildPubPackage (file:///home/travis/build/dart-lang/dartdoc/tool/grind.dart:847:10)
#3      _LibraryMirror._invoke (dart:mirrors-patch/mirrors_impl.dart:1089:36)
#4      _ObjectMirror.invoke (dart:mirrors-patch/mirrors_impl.dart:242:25)
#5      TaskDiscovery.discoverDeclaration.<anon> (package:grinder/src/discover_tasks.dart:77:38)
#6      _rootRun (dart:async/zone.dart:1190:13)
#7      _CustomZone.run (dart:async/zone.dart:1093:19)
#8      _runZoned (dart:async/zone.dart:1630:10)
#9      runZoned (dart:async/zone.dart:1550:10)
#10     ZonedValue.withValue (package:grinder/src/utils.dart:113:12)
#11     GrinderTask.execute (package:grinder/src/grinder_task.dart:63:27)
#12     Grinder._invokeTask (package:grinder/src/grinder.dart:193:27)
#13     Grinder.start.<anon> (package:grinder/src/grinder.dart:168:16)
#14     Future.forEach.<anon> (dart:async/future.dart:507:26)
#15     Future.doWhile.<anon> (dart:async/future.dart:549:26)
#16     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#17     _RootZone.bindUnaryCallbackGuarded.<anon> (dart:async/zone.dart:1423:26)
#18     Future.doWhile (dart:async/future.dart:565:18)
#19     Future.forEach (dart:async/future.dart:505:12)
#20     Grinder.start (package:grinder/src/grinder.dart:167:21)
#21     runTasks (package:grinder/src/cli.dart:67:38)
#22     grind (package:grinder/grinder.dart:46:12)
#23     main (file:///home/travis/build/dart-lang/dartdoc/tool/grind.dart:17:35)
The command "./tool/travis.sh" exited with 1.
cache.2
store build cache
```

**Comment by jcollins-g** [comment]
root cause:  dart-lang/pub#2528

will implement workaround.
