### ISSUE TITLE
NPE at PubPackageBuilder.processLibrary

### ISSUE THREAD

**Issue by isoos** [dart-lang/dartdoc#2243]
On pub.dev for `value_animation_progress/1.0.0+2`:

````
NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      PubPackageBuilder.processLibrary (package:dartdoc/src/model/package_builder.dart:233:38)
<asynchronous suspension>
#2      PubPackageBuilder._parseLibraries (package:dartdoc/src/model/package_builder.dart:273:23)
#3      PubPackageBuilder.getLibraries (package:dartdoc/src/model/package_builder.dart:412:11)
#4      PubPackageBuilder.buildPackageGraph (package:dartdoc/src/model/package_builder.dart:72:11)
#5      Dartdoc.generateDocsBase (package:dartdoc/dartdoc.dart:175:41)
#6      Dartdoc.generateDocs (package:dartdoc/dartdoc.dart:216:34)
````

**Comment by srawlins** [comment]
This appears to be fixed at HEAD. Likely during other `definingLibrary` fixes.
