### ISSUE TITLE
Unknown type <X> exception (referencing missing type in markdown)

### ISSUE THREAD

**Issue by isoos** [dart-lang/dartdoc#2263]
I think this kind of error should not prevent dartdoc to complete.

Example:
````
STDERR:
  warning: unresolved doc reference [providers], from masamune.gui.UIAuth: (file:///tmp/pub-dartlang-dartdocRJNWCW/pkg/lib/widget/uiauth.dart:5:7)
  warning: unresolved doc reference [value.text()], from masamune.gui.UIPanel: (file:///tmp/pub-dartlang-dartdocRJNWCW/pkg/lib/widget/uipanel.dart:7:7)
  warning: unresolved doc reference [value.get())], from masamune.gui.UIPanel: (file:///tmp/pub-dartlang-dartdocRJNWCW/pkg/lib/widget/uipanel.dart:7:7)
  warning: unresolved doc reference [value.text()], from masamune.gui.UIWidget: (file:///tmp/pub-dartlang-dartdocRJNWCW/pkg/lib/component/uiwidget.dart:7:16)
  warning: unresolved doc reference [value.get())], from masamune.gui.UIWidget: (file:///tmp/pub-dartlang-dartdocRJNWCW/pkg/lib/component/uiwidget.dart:7:16)
Unhandled exception:
Unknown type MultiplyDefinedElementImpl
#0      new ModelElement.from (package:dartdoc/src/model/model_element.dart:340:34)
#1      new ModelElement.fromElement (package:dartdoc/src/model/model_element.dart:189:25)
#2      _MarkdownCommentReference._findAnalyzerReferences (package:dartdoc/src/markdown_processor.dart:686:42)
#3      _MarkdownCommentReference.computeReferredElement (package:dartdoc/src/markdown_processor.dart:397:17)
#4      _getMatchingLinkElement (package:dartdoc/src/markdown_processor.dart:214:12)
#5      _makeLinkNode (package:dartdoc/src/markdown_processor.dart:764:16)
#6      new MarkdownDocument.withElementLinkResolver.linkResolver (package:dartdoc/src/markdown_processor.dart:859:14)
#7      LinkSyntax._resolveReferenceLink (package:markdown/src/inline_parser.dart:799:26)
````

https://storage.googleapis.com/pub-packages/packages/masamune_gui-0.1.0.tar.gz

**Comment by srawlins** [comment]
I can reproduce this at dartdoc HEAD.
