### ISSUE TITLE
NoSuchMethodError: The getter 'inheritanceManager' was called on null.

### ISSUE THREAD

**Issue by isoos** [dart-lang/dartdoc#2264]
https://pub.dev/documentation/fid_widgets/latest/log.txt
https://gitlab.com/flutter-dev-israel/fid-widgets
https://storage.googleapis.com/pub-packages/packages/fid_widgets-0.0.6.tar.gz

````
NoSuchMethodError: The getter 'inheritanceManager' was called on null.
Receiver: null
Tried calling: inheritanceManager
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      Class._inheritedElements (package:dartdoc/src/model/class.dart:306:41)
#2      Class.inheritedMethods (package:dartdoc/src/model/class.dart:159:37)
#3      Class.instanceMethods (package:dartdoc/src/model/class.dart:61:45)
#4      Container.allModelElements (package:dartdoc/src/model/container.dart:39:9)
#5      Class.allModelElements (package:dartdoc/src/model/class.dart:75:17)
#6      Library.modelElementsMap.<anonymous closure> (package:dartdoc/src/model/library.dart:598:15)
#7      ExpandIterator.moveNext (dart:_internal/iterable.dart:484:31)
#8      ExpandIterator.moveNext (dart:_internal/iterable.dart:478:31)
#9      Iterable.forEach (dart:core/iterable.dart:279:23)
#10     Library.modelElementsMap (package:dartdoc/src/model/library.dart:615:15)
#11     Library.allModelElements (package:dartdoc/src/model/library.dart:630:33)
#12     PackageGraph.allModelElements.<anonymous closure>.<anonymous closure> (package:dartdoc/src/model/package_graph.dart:882:48)
#13     SetMixin.forEach (dart:collection/set.dart:148:30)
#14     PackageGraph.allModelElements.<anonymous closure> (package:dartdoc/src/model/package_graph.dart:881:18)
#15     SetMixin.forEach (dart:collection/set.dart:148:30)
#16     PackageGraph.allModelElements (package:dartdoc/src/model/package_graph.dart:875:52)
#17     PackageGraph.precacheLocalDocs (package:dartdoc/src/model/package_graph.dart:120:19)
#18     _SyncIterator.moveNext (dart:core-patch/core_patch.dart:146:23)
#19     new List.from (dart:core-patch/array_patch.dart:47:19)
#20     Iterable.toList (dart:core/iterable.dart:400:12)
#21     PackageGraph.initializePackageGraph (package:dartdoc/src/model/package_graph.dart:71:47)
#22     PubPackageBuilder.buildPackageGraph (package:dartdoc/src/model/package_builder.dart:73:20)
<asynchronous suspension>
#23     Dartdoc.generateDocsBase (package:dartdoc/dartdoc.dart:175:41)
#24     Dartdoc.generateDocs (package:dartdoc/dartdoc.dart:216:34)
#25     main (file:///project/pkg/pub_dartdoc/bin/pub_dartdoc.dart:27:33)
````

**Comment by devoncarew** [comment]
cc @srawlins (if you're not already subscribed to the repo you may want to)

**Comment by srawlins** [comment]
This should also have been fixed in https://github.com/dart-lang/dartdoc/commit/ed8ac3c73822ca8396f192c7ae8920dd20cd8ce4.
