### ISSUE TITLE
Latest version of dartdoc fails, "Invalid Arguments"

### ISSUE THREAD

**Issue by Vbbab** [dart-lang/dartdoc#2364]
The latest version of `dartdoc` from pub, v`0.34.0`, fails when documenting a `flutter` project.

`dart-sdk` version: `Dart SDK version: 2.9.3 (stable) (Tue Sep 8 11:21:00 2020 +0200) on "windows_x64"`

Full dump:
```
dartdoc failed: Invalid argument(s): join(null, "bin", "cache", "dart-sdk"): part 0 was null, but part 1 was not.
#0      _validateArgList (package:path/src/context.dart:1103:5)
#1      Context.join (package:path/src/context.dart:242:5)
#2      join (package:path/path.dart:265:13)
#3      createDartdocOptions.<anonymous closure> (package:dartdoc/src/dartdoc_options.dart:1587:16)
#4      DartdocSyntheticOption._valueAtFromSynthetic (package:dartdoc/src/dartdoc_options.dart:798:44)
#5      DartdocOptionArgSynth.valueAt (package:dartdoc/src/dartdoc_options.dart:756:12)
#6      DartdocOptionContext.sdkDir (package:dartdoc/src/dartdoc_options.dart:1405:44)
#7      PubPackageBuilder.sdk (package:dartdoc/src/model/package_builder.dart:81:60)
#8      PubPackageBuilder.buildPackageGraph (package:dartdoc/src/model/package_builder.dart:67:7)
#9      Dartdoc.generateDocsBase (package:dartdoc/dartdoc.dart:175:41)
#10     Dartdoc.generateDocs (package:dartdoc/dartdoc.dart:216:34)
#11     _rootRun (dart:async/zone.dart:1190:13)
#12     _CustomZone.run (dart:async/zone.dart:1093:19)
#13     _runZoned (dart:async/zone.dart:1630:10)
#14     runZonedGuarded (dart:async/zone.dart:1618:12)
#15     Dartdoc.executeGuarded (package:dartdoc/dartdoc.dart:475:5)
#16     main (file:///C:/b/s/w/ir/cache/builder/sdk/third_party/pkg/dartdoc/bin/dartdoc.dart:24:11)
<asynchronous suspension>
#17     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by jcollins-g** [comment]
Flutter is not installed correctly and/or your FLUTTER_ROOT environment variable is not set.

**Comment by jcollins-g** [comment]
If you need support getting Flutter working, please try the Flutter discord channel or other resources at https://flutter.dev/community
