### ISSUE TITLE
NPE with documentationComment

### ISSUE THREAD

**Issue by isoos** [dart-lang/dartdoc#2402]
Multiple packages are affected, for example:
- https://pub.dev/packages/hotreloader (https://github.com/dart-lang/pub-dev/issues/4166)
- https://pub.dev/packages/ninja_prime (https://github.com/dart-lang/pub-dev/issues/4167)

With `dartdoc 0.36.0`, the exception is:

```
dartdoc failed: NoSuchMethodError: The getter 'hasNodoc' was called on null.
Receiver: null
Tried calling: hasNodoc
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      Accessor.computeDocumentationComment (package:dartdoc/src/model/accessor.dart:62:25)
#2      DocumentationComment.documentationComment (package:dartdoc/src/model/documentation_comment.dart:39:31)
#3      ModelElement.computeDocumentationFrom (package:dartdoc/src/model/model_element.dart:592:9)
#4      ModelElement.documentationFrom (package:dartdoc/src/model/model_element.dart:572:28)
#5      PackageGraph.precacheLocalDocs.<anonymous closure>.precacheOneElement.<anonymous closure> (package:dartdoc/src/model/package_graph.dart:109:16)
#6      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:165:25)
#7      Future.wait (dart:async/future.dart:406:26)
#8      PackageGraph.initializePackageGraph (package:dartdoc/src/model/package_graph.dart:74:18)
#9      PubPackageBuilder.buildPackageGraph (package:dartdoc/src/model/package_builder.dart:77:20)
<asynchronous suspension>
#10     Dartdoc.generateDocsBase (package:dartdoc/dartdoc.dart:182:41)
#11     Dartdoc.generateDocs (package:dartdoc/dartdoc.dart:223:34)
#12     Dartdoc.executeGuarded.<anonymous closure> (package:dartdoc/dartdoc.dart:500:15)
#13     _rootRun (dart:async/zone.dart:1190:13)
#14     _CustomZone.run (dart:async/zone.dart:1093:19)
#15     _runZoned (dart:async/zone.dart:1630:10)
#16     runZonedGuarded (dart:async/zone.dart:1618:12)
#17     Dartdoc.executeGuarded (package:dartdoc/dartdoc.dart:498:5)
#18     main (file:///Users/isoos/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.36.0/bin/dartdoc.dart:26:11)
```

Prior to that, with `dartdoc 0.35.0` the exception was:

```
dartdoc failed: NoSuchMethodError: The getter 'documentationComment' was called on null.
Receiver: null
Tried calling: documentationComment
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      Accessor.computeDocumentationComment (package:dartdoc/src/model/accessor.dart:67:44)
#2      DocumentationComment.documentationComment (package:dartdoc/src/model/documentation_comment.dart:39:31)
#3      ModelElement.computeDocumentationFrom (package:dartdoc/src/model/model_element.dart:589:9)
#4      ModelElement.documentationFrom (package:dartdoc/src/model/model_element.dart:569:28)
#5      PackageGraph.precacheLocalDocs.<anonymous closure>.precacheOneElement.<anonymous closure> (package:dartdoc/src/model/package_graph.dart:109:16)
#6      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:165:25)
#7      Future.wait (dart:async/future.dart:406:26)
#8      PackageGraph.initializePackageGraph (package:dartdoc/src/model/package_graph.dart:74:18)
#9      PubPackageBuilder.buildPackageGraph (package:dartdoc/src/model/package_builder.dart:77:20)
<asynchronous suspension>
#10     Dartdoc.generateDocsBase (package:dartdoc/dartdoc.dart:182:41)
#11     Dartdoc.generateDocs (package:dartdoc/dartdoc.dart:223:34)
#12     Dartdoc.executeGuarded.<anonymous closure> (package:dartdoc/dartdoc.dart:500:15)
#13     _rootRun (dart:async/zone.dart:1190:13)
#14     _CustomZone.run (dart:async/zone.dart:1093:19)
#15     _runZoned (dart:async/zone.dart:1630:10)
#16     runZonedGuarded (dart:async/zone.dart:1618:12)
#17     Dartdoc.executeGuarded (package:dartdoc/dartdoc.dart:498:5)
#18     main (file:///Users/isoos/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.35.0/bin/dartdoc.dart:26:11)
```

**Comment by CaptainIRS** [comment]
Minimal example that fails with similar error:
```dart
class x {}

extension y on x {
  static int a;
}
```

**Comment by jcollins-g** [comment]
This is a "never happen" error -- something has gone wrong where Dartdoc sees an accessor it can not find an enclosing field for.

**Comment by jcollins-g** [comment]
This is a problem in 0.35.0 as well:  https://github.com/flutter/flutter/pull/68654/checks?check_run_id=1283519449

My guess is some key package somewhere added a construct like @CaptainIRS mentioned and therefore everyone depending on it is bumping into the crash.

**Comment by jcollins-g** [comment]
I have found the issue.  Initialization and connection of Accessors and Fields was incomplete and partially dependent on the order in which elements are initialized.  Working on a fix; given this is P0 I will put out a patch release once complete.

**Comment by jonataslaw** [comment]
Hi, I think this problem still exists, even after the merge.
I just uploaded Getx 2.15 to pub.dev, and I'm having the same problem:
https://pub.dev/packages/get/score

![image](https://user-images.githubusercontent.com/35742643/97118203-7d471900-16e7-11eb-95b9-bb03c4cb16d9.png)

**Comment by isoos** [comment]
@jonataslaw: pub.dev did not deployed this version yet (it uses `0.35.0`).

**Comment by jonataslaw** [comment]
> @jonataslaw: pub.dev did not deployed this version yet (it uses `0.35.0`).

Thanks for the quick response!

**Comment by jonataslaw** [comment]
After update, the problem persists
![image](https://user-images.githubusercontent.com/35742643/98614790-ed54c200-22d7-11eb-9b42-bb1b284318cd.png)

**Comment by jonataslaw** [comment]
After update, the problem persists
![97118203-7d471900-16e7-11eb-95b9-bb03c4cb16d9](https://user-images.githubusercontent.com/35742643/98614846-09f0fa00-22d8-11eb-9767-996bff022b38.png)
