### ISSUE TITLE
coverage builds hanging on travis

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/dartdoc#2412]
from head: https://travis-ci.org/github/dart-lang/dartdoc/jobs/740754863

```
dart2-model_test.dart: + DARTDOC_COVERAGE_DATA=/tmp/dartdoc_coverage_dataIPQYRN /home/travis/dart-sdk/bin/dart --disable-service-auth-codes --enable-vm-service:0 --pause-isolates-on-exit --enable-asserts test/end2end/model_test.dart
dart2-model_test.dart: NoSuchMethodError: The getter 'enabled' was called on null.
dart2-model_test.dart: Receiver: null
dart2-model_test.dart: Tried calling: enabled
dart2-model_test.dart: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
dart2-model_test.dart: #1      runDartdev (package:dartdev/dartdev.dart:114:19)
dart2-model_test.dart: #2      main (file:///b/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart:11:9)
dart2-model_test.dart: #3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:32)
dart2-model_test.dart: #4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
dart2-model_test.dart:
dart2-model_test.dart: .
dart2-model_test.dart: Attempt:11 waiting for isolate vm-isolate to check in
dart2-model_test.dart: Attempt:11 waiting for isolate dartdev to check in
dart2-model_test.dart: Attempt:12 waiting for isolate vm-isolate to check in
dart2-model_test.dart: Attempt:12 waiting for isolate dartdev to check in
dart2-model_test.dart: Attempt:13 waiting for isolate vm-isolate to check in
dart2-model_test.dart: Attempt:13 waiting for isolate dartdev to check in
dart2-model_test.dart: Attempt:14 waiting for isolate vm-isolate to check in
dart2-model_test.dart: Attempt:14 waiting for isolate dartdev to check in
dart2-model_test.dart: Attempt:15 waiting for isolate vm-isolate to check in
dart2-model_test.dart: Attempt:15 waiting for isolate dartdev to check in
dart2-model_test.dart: Attempt:16 waiting for isolate vm-isolate to check in
dart2-model_test.dart: Attempt:16 waiting for isolate dartdev to check in
```

**Comment by jcollins-g** [comment]
Closing.  The workaround in #2413 is pretty simple and we can remove it once dart-lang/sdk#44027 is fixed.
