### ISSUE TITLE
dartdoc 0.32.4 produces errors when encountering late private variables.

### ISSUE THREAD

**Issue by simphotonics** [dart-lang/dartdoc#2475]
Dartdoc throws errors when encountering **late private** class variables and produces a file called `late.html` (see below). 
```Console
$ dartdoc --version
dartdoc version: 0.32.4
```

```Console
$ dart --version
Dart SDK version: 2.10.4 (stable) (Unknown timestamp) on "linux_x64"
```

To reproduce the error one could clone the sample project [analyzer_test](https://github.com/simphotonics/analyzer_test) or generate a new Dart project and define the class `MyClass` in `lib\my_class.dart`: 
```Dart
class MyClass {
  MyClass(int a) {
    a = this.a;
    _b = a;
  }

  late final int _b;  // <------ This variable is not handled as expected.
  late final int a;

  @override
  String toString() {
  return _b.toString();
   }
}
```
followed by running dartdoc:
```Console
$ dartdoc
Documenting analyzer_test...
Initialized dartdoc with 40 libraries in 21.1 seconds
Generating docs for library analyzer_test from package:analyzer_test/analyzer_test.dart...
Generating docs for library my_class from package:analyzer_test/my_class.dart...
  error: failed to write file at: my_class/MyClass/late.html, for symbol my_class.MyClass.late: (file:///home/dan/WORK/RemoteFlutterProjects/analyzer_test/lib/my_class.dart:7:3)
            Dartdoc generates a path and filename to write to for each symbol.
            my_class.MyClass.late conflicts with another symbol in the generated path, and
            therefore can not be written out.  Changing the name, library name, or
            class name (if appropriate) of one of the conflicting items can resolve
            the conflict.   Alternatively, use the @nodoc tag in one symbol's
            documentation comments to hide it.
Validating docs...
found 0 warnings and 1 error
Documented 2 public libraries in 1.1 seconds

dartdoc failed: dartdoc encountered 1 errors while processing..
#0      Dartdoc.generateDocs (package:dartdoc/dartdoc.dart:231:9)
<asynchronous suspension>
#1      Dartdoc.executeGuarded.<anonymous closure> (package:dartdoc/dartdoc.dart:500:15)
#2      _rootRun (dart:async/zone.dart:1190:13)
#3      _CustomZone.run (dart:async/zone.dart:1093:19)
#4      _runZoned (dart:async/zone.dart:1630:10)
#5      runZonedGuarded (dart:async/zone.dart:1618:12)
#6      Dartdoc.executeGuarded (package:dartdoc/dartdoc.dart:498:5)
#7      main (file:///tmp/tmpRN2vKk/dart-2.10.4/dart/third_party/pkg/dartdoc/bin/dartdoc.dart:24:11)
<asynchronous suspension>
#8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

Below a screenshot of the file late.html.
![Screenshot_2021-01-05_19-17-03](https://user-images.githubusercontent.com/5442704/103689445-3a2ce000-4f8b-11eb-8ddb-48abb169edac.png)

**Comment by simphotonics** [comment]
The issue mentioned above does not occur when using the latest version `dartdoc: ^0.38.0`.

Until the updates make it to the `dartdoc` version that comes bundled with the Dart SDK one could use the [dartdoc package](https://pub.dev/packages/dartdoc) to generate documentation. 
Steps involved: 
1. Include dartdoc ^0.38.0 under `dev_dependencies` in your `pubspec.yaml` file.
2. Issue the command: 
    ```Console
   $ pub global activate dartdoc
   ```
3. Generate the documentation by invoking the activated version of `dartdoc` from the package root directory.

Alternatively, one could add the `@nodoc` tag to the comment line of each private late class variable: 
```Dart
/// @nodoc
late final int _b
``` 

Closing this issue.
