### ISSUE TITLE
dartdoc failed: NoSuchMethodError: The getter 'element' was called on null.

### ISSUE THREAD

**Issue by nicki-klexx** [dart-lang/dartdoc#2505]
If I try to run dartdoc in my project I get this error after a while:

```
$ dartdoc
Documenting <APP>                                                                                                                                                                                                 -
dartdoc failed: NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      new ElementType.from (package:dartdoc/src/element_type.dart:29:11)
#2      new Extension (package:dartdoc/src/model/extension.dart:21:21)
#3      ModelElement._from (package:dartdoc/src/model/model_element.dart:330:14)
#4      new ModelElement.from (package:dartdoc/src/model/model_element.dart:278:40)
#5      Library.extensions.<anonymous closure> (package:dartdoc/src/model/library.dart:202:34)
#6      MappedIterator.moveNext (dart:_internal/iterable.dart:389:20)
#7      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:198:26)
#8      new _List._ofOther (dart:core-patch/array.dart:106:43)
#9      new _List.of (dart:core-patch/array.dart:57:18)
#10     new List.of (dart:core-patch/array_patch.dart:52:20)
#11     Iterable.toList (dart:core/iterable.dart:366:12)
#12     Library.extensions (package:dartdoc/src/model/library.dart:203:10)
#13     Library.modelElementsMap (package:dartdoc/src/model/library.dart:607:17)
#14     Library.allModelElements (package:dartdoc/src/model/library.dart:647:33)
#15     PackageGraph.allModelElements.<anonymous closure>.<anonymous closure> (package:dartdoc/src/model/package_graph.dart:915:48)
#16     SetMixin.forEach (dart:collection/set.dart:142:30)
#17     PackageGraph.allModelElements.<anonymous closure> (package:dartdoc/src/model/package_graph.dart:914:18)
#18     SetMixin.forEach (dart:collection/set.dart:142:30)
#19     PackageGraph.allModelElements (package:dartdoc/src/model/package_graph.dart:908:52)
#20     PackageGraph.precacheLocalDocs.sync_op (package:dartdoc/src/model/package_graph.dart:121:19)
#21     _SyncIterator.moveNext (dart:core-patch/core_patch.dart:181:26)
#22     Future.wait (dart:async/future.dart:409:26)
#23     PackageGraph.initializePackageGraph (package:dartdoc/src/model/package_graph.dart:73:18)
#24     PubPackageBuilder.buildPackageGraph (package:dartdoc/src/model/package_builder.dart:72:20)
<asynchronous suspension>
#25     Dartdoc.generateDocsBase (package:dartdoc/dartdoc.dart:182:20)
<asynchronous suspension>
#26     Dartdoc.generateDocs (package:dartdoc/dartdoc.dart:223:28)
<asynchronous suspension>
#27     Dartdoc.executeGuarded.<anonymous closure> (package:dartdoc/dartdoc.dart:500:9)
<asynchronous suspension>
```

```
$ flutter --version
Flutter 1.26.0-12.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision a706cd2112 (vor 3 Wochen) • 2021-01-14 18:20:26 -0500
Engine • revision effb529ece
Tools • Dart 2.12.0 (build 2.12.0-224.0.dev)
```

```
$ dart --version     
Dart SDK version: 2.12.0-224.0.dev (dev) (Thu Jan 14 08:05:52 2021 -0800) on "linux_x64"
```

```
$ dartdoc --version
dartdoc version: 0.38.0
```

**Comment by parlough** [comment]
Perhaps the discussion in https://github.com/dart-lang/dartdoc/issues/2479 will be of help.

**Comment by nicki-klexx** [comment]
Yes, thank you!

`pub global run dartdoc` works for me.

Thank you very much! I didn't find this for days. :see_no_evil:
