### ISSUE TITLE
Failed to run dartdoc with the package on pub.dev

### ISSUE THREAD

**Issue by AlexV525** [dart-lang/dartdoc#2577]
Please check https://pub.dev/packages/wechat_assets_picker/score for the full detail.

The dartdoc generate was failed without any useful informations. I ran the generate locally and the doc generated without error.

```shell
Unhandled exception:
NoSuchMethodError: The getter 'flow' was called on null.
Receiver: null
Tried calling: flow
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      ResolverVisitor.startNullAwarePropertyAccess (package:analyzer/src/generated/resolver.dart:758:23)
#2      ResolverVisitor.visitPropertyAccess (package:analyzer/src/generated/resolver.dart:1730:5)
#3      PropertyAccessImpl.accept (package:analyzer/src/dart/ast/ast.dart:8398:49)
#4      BinaryExpressionResolver._resolveEqual (package:analyzer/src/dart/resolver/binary_expression_resolver.dart:111:10)
#5      BinaryExpressionResolver.resolve (package:analyzer/src/dart/resolver/binary_expression_resolver.dart:58:7)
#6      ResolverVisitor.visitBinaryExpression (package:analyzer/src/generated/resolver.dart:897:31)
#7      BinaryExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:954:49)
#8      BinaryExpressionResolver._resolveLogicalOr (package:analyzer/src/dart/resolver/binary_expression_resolver.dart:224:11)
#9      BinaryExpressionResolver.resolve (package:analyzer/src/dart/resolver/binary_expression_resolver.dart:63:7)
#10     ResolverVisitor.visitBinaryExpression (package:analyzer/src/generated/resolver.dart:897:31)
#11     BinaryExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:954:49)
#12     ResolverVisitor.visitAssertInitializer (package:analyzer/src/generated/resolver.dart:856:21)
#13     AssertInitializerImpl.accept (package:analyzer/src/dart/ast/ast.dart:517:49)
#14     AstResolver.resolve (package:analyzer/src/summary2/ast_resolver.dart:85:10)
#15     ConstructorInitializerResolver._initializers (package:analyzer/src/summary2/constructor_initializer_resolver.dart:68:20)
#16     ConstructorInitializerResolver._constructor (package:analyzer/src/summary2/constructor_initializer_resolver.dart:54:5)
#17     ConstructorInitializerResolver.resolve (package:analyzer/src/summary2/constructor_initializer_resolver.dart:31:11)
#18     LibraryBuilder.resolveConstructors (package:analyzer/src/summary2/library_builder.dart:240:53)
#19     Linker._resolveConstructors (package:analyzer/src/summary2/link.dart:210:15)
#20     Linker._buildOutlines (package:analyzer/src/summary2/link.dart:95:5)
#21     Linker.link (package:analyzer/src/summary2/link.dart:76:5)
#22     link (package:analyzer/src/summary2/link.dart:32:10)
#23     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:215:24)
#24     LibraryContext.load2.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:262:17)
#25     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#26     LibraryContext.load2 (package:analyzer/src/dart/analysis/library_context.dart:260:12)
#27     new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:77:5)
#28     AnalysisDriver._createLibraryContext.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1538:27)
#29     _rootRun (dart:async/zone.dart:1190:13)
#30     _CustomZone.run (dart:async/zone.dart:1093:19)
#31     _runZoned (dart:async/zone.dart:1630:10)
#32     runZoned (dart:async/zone.dart:1550:10)
#33     NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42:12)
#34     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1536:33)
#35     AnalysisDriver._computeResolvedLibrary2.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1402:28)
#36     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#37     AnalysisDriver._computeResolvedLibrary2 (package:analyzer/src/dart/analysis/driver.dart:1400:20)
#38     AnalysisDriver._computeResolvedLibrary.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1393:15)
#39     _rootRun (dart:async/zone.dart:1190:13)
#40     _CustomZone.run (dart:async/zone.dart:1093:19)
#41     _runZoned (dart:async/zone.dart:1630:10)
#42     runZoned (dart:async/zone.dart:1550:10)
#43     NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42:12)
#44     AnalysisDriver._computeResolvedLibrary (package:analyzer/src/dart/analysis/driver.dart:1392:40)
#45     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:962:22)
#46     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2013:24)
<asynchronous suspension>
#47     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1936:5)
#48     ContextBuilderImpl.createContext (package:analyzer/src/dart/analysis/context_builder.dart:64:17)
#49     new AnalysisContextCollectionImpl (package:analyzer/src/dart/analysis/analysis_context_collection.dart:55:36)
#50     PubPackageBuilder.contextCollection (package:dartdoc/src/model/package_builder.dart:121:28)
#51     PubPackageBuilder.processLibrary (package:dartdoc/src/model/package_builder.dart:156:27)
#52     PubPackageBuilder._parseLibraries (package:dartdoc/src/model/package_builder.dart:215:23)
#53     PubPackageBuilder.getLibraries (package:dartdoc/src/model/package_builder.dart:402:11)
<asynchronous suspension>
#54     PubPackageBuilder.buildPackageGraph (package:dartdoc/src/model/package_builder.dart:71:11)
<asynchronous suspension>
#55     Dartdoc.generateDocsBase (package:dartdoc/dartdoc.dart:182:41)
#56     Dartdoc.generateDocs (package:dartdoc/dartdoc.dart:223:34)
#57     main (file:///project/pkg/pub_dartdoc/bin/pub_dartdoc.dart:21:33)
<asynchronous suspension>
#58     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#59     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)


#0      LibraryContext._throwLibraryCycleLinkException (package:analyzer/src/dart/analysis/library_context.dart:329:5)
#1      LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:220:11)
#2      LibraryContext.load2.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:262:17)
#3      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#4      LibraryContext.load2 (package:analyzer/src/dart/analysis/library_context.dart:260:12)
#5      new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:77:5)
#6      AnalysisDriver._createLibraryContext.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1538:27)
#7      _rootRun (dart:async/zone.dart:1190:13)
#8      _CustomZone.run (dart:async/zone.dart:1093:19)
#9      _runZoned (dart:async/zone.dart:1630:10)
#10     runZoned (dart:async/zone.dart:1550:10)
#11     NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42:12)
#12     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1536:33)
#13     AnalysisDriver._computeResolvedLibrary2.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1402:28)
#14     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#15     AnalysisDriver._computeResolvedLibrary2 (package:analyzer/src/dart/analysis/driver.dart:1400:20)
#16     AnalysisDriver._computeResolvedLibrary.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1393:15)
#17     _rootRun (dart:async/zone.dart:1190:13)
#18     _CustomZone.run (dart:async/zone.dart:1093:19)
#19     _runZoned (dart:async/zone.dart:1630:10)
#20     runZoned (dart:async/zone.dart:1550:10)
#21     NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42:12)
#22     AnalysisDriver._computeResolvedLibrary (package:analyzer/src/dart/analysis/driver.dart:1392:40)
#23     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:962:22)
#24     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2013:24)
<asynchronous suspension>
#25     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1936:5)
#26     ContextBuilderImpl.createContext (package:analyzer/src/dart/analysis/context_builder.dart:64:17)
#27     new AnalysisContextCollectionImpl (package:analyzer/src/dart/analysis/analysis_context_collection.dart:55:36)
#28     PubPackageBuilder.contextCollection (package:dartdoc/src/model/package_builder.dart:121:28)
#29     PubPackageBuilder.processLibrary (package:dartdoc/src/model/package_builder.dart:156:27)
#30     PubPackageBuilder._parseLibraries (package:dartdoc/src/model/package_builder.dart:215:23)
#31     PubPackageBuilder.getLibraries (package:dartdoc/src/model/package_builder.dart:402:11)
<asynchronous suspension>
#32     PubPackageBuilder.buildPackageGraph (package:dartdoc/src/model/package_builder.dart:71:11)
<asynchronous suspension>
#33     Dartdoc.generateDocsBase (package:dartdoc/dartdoc.dart:182:41)
#34     Dartdoc.generateDocs (package:dartdoc/dartdoc.dart:223:34)
#35     main (file:///project/pkg/pub_dartdoc/bin/pub_dartdoc.dart:21:33)
<asynchronous suspension>
#36     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by CaptainIRS** [comment]
It seems pub.dev is still running dartdoc 0.39.0 as seen in the [log](https://pub.dev/documentation/wechat_assets_picker/5.0.1/log.txt). Once pub.dev's dartdoc version is upgraded to 0.40.0, it should work properly as no error is thrown starting from f3e803cf.

**Comment by AlexV525** [comment]
> Once pub.dev's dartdoc version is upgraded to 0.40.0, it should work properly as no error is thrown starting from [f3e803c](https://github.com/dart-lang/dartdoc/commit/f3e803cf5b97a2c868252ee8fac3a5858ee2bf44).

SGTM. Thanks for the clarify.

**Comment by AlexV525** [comment]
Looks good now.
![image](https://user-images.githubusercontent.com/15884415/111401869-19100a80-8705-11eb-880a-0b7597cf6872.png)

**Comment by AlexV525** [comment]
The issue is still exist with some specific cases, please see the mentioned issue.
