### ISSUE TITLE
Regression for dartdoc 0.45.0 -> 1.0.0: protobuf version 2.0.0 fails

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/dartdoc#2716]
Reproduction steps:
```bash
PACKAGE=protobuf
VERSION=2.0.0

cd $(mktemp -d)
curl -L "https://storage.googleapis.com/pub-packages/packages/$PACKAGE-$VERSION.tar.gz" | tar -xz
# This works
dart pub global activate dartdoc 0.45.0
dart pub global run dartdoc
# This won't work
dart pub global activate dartdoc 1.0.0
dart pub global run dartdoc
```

Stack trace:
```
dartdoc 1.0.0 (/home/jonasfj/.pub-cache/global_packages/dartdoc/bin/dartdoc.dart-2.14.0-293.0.dev.snapshot) failed: Bad state: T extends GeneratedMessage cannot have parameters
#0      ModelElement.parameters (package:dartdoc/src/model/model_element.dart:980:7)
#1      TypeParameter.referenceChildren (package:dartdoc/src/model/type_parameter.dart:75:23)
#2      DefinedElementType.referenceChildren (package:dartdoc/src/element_type.dart:367:20)
#3      Extension.referenceChildren (package:dartdoc/src/model/extension.dart:127:23)
#4      CommentReferable.referenceBy (package:dartdoc/src/model/comment_referable.dart:112:11)
#5      CommentReferable.referenceBy (package:dartdoc/src/model/comment_referable.dart:122:25)
#6      _getMatchingLinkElementCommentReferable (package:dartdoc/src/markdown_processor.dart:268:31)
#7      getMatchingLinkElement (package:dartdoc/src/markdown_processor.dart:964:16)
#8      _makeLinkNode (package:dartdoc/src/markdown_processor.dart:913:16)
#9      new MarkdownDocument.withElementLinkResolver.linkResolver (package:dartdoc/src/markdown_processor.dart:1062:14)
#10     LinkSyntax._resolveReferenceLink (package:markdown/src/inline_parser.dart:1057:34)
#11     LinkSyntax._tryCreateReferenceLink (package:markdown/src/inline_parser.dart:1085:12)
#12     LinkSyntax.close (package:markdown/src/inline_parser.dart:1028:12)
#13     InlineParser._linkOrImage (package:markdown/src/inline_parser.dart:152:29)
#14     InlineParser.parse (package:markdown/src/inline_parser.dart:108:9)
#15     MarkdownDocument._parseInlineContent (package:dartdoc/src/markdown_processor.dart:1111:67)
#16     MarkdownDocument._parseInlineContent (package:dartdoc/src/markdown_processor.dart:1116:9)
#17     MarkdownDocument.parseMarkdownText (package:dartdoc/src/markdown_processor.dart:1101:5)
#18     Documentation._parseDocumentation (package:dartdoc/src/model/documentation.dart:73:21)
#19     Documentation._renderDocumentation (package:dartdoc/src/model/documentation.dart:48:23)
#20     Documentation.asOneLiner (package:dartdoc/src/model/documentation.dart:40:7)
#21     ModelElement.oneLineDoc (package:dartdoc/src/model/model_element.dart:926:43)
#22     _renderExtension_partial_callable_6 (package:dartdoc/src/generator/templates.aot_renderers_for_html.dart:4690:25)
#23     renderExtension (package:dartdoc/src/generator/templates.aot_renderers_for_html.dart:4226:24)
#24     HtmlAotTemplates.renderExtension (package:dartdoc/src/generator/templates.dart:143:7)
#25     DartdocGeneratorBackend.generateExtension (package:dartdoc/src/generator/dartdoc_generator_backend.dart:171:29)
#26     GeneratorFrontEnd._generateDocs (package:dartdoc/src/generator/generator_frontend.dart:122:29)
#27     GeneratorFrontEnd.generate (package:dartdoc/src/generator/generator_frontend.dart:21:5)
#28     Dartdoc.generateDocsBase (package:dartdoc/dartdoc.dart:213:21)
<asynchronous suspension>
#29     Dartdoc.generateDocs (package:dartdoc/dartdoc.dart:249:28)
<asynchronous suspension>
#30     Dartdoc.executeGuarded.<anonymous closure> (package:dartdoc/dartdoc.dart:512:9)
<asynchronous suspension>
```

**Comment by devoncarew** [comment]
@jonasfj - thanks for the bug report. Are you seeing this for additional packages?

**Comment by devoncarew** [comment]
I can reproduce this when running the lastest dartdoc from source against dart-lang/protobuf from master:

```
Documenting protobuf...
Initialized dartdoc with 44 libraries in 14.0 seconds
Generating docs for library protobuf.meta from package:protobuf/meta.dart...
Generating docs for library protobuf from package:protobuf/protobuf.dart...
  warning: protobuf has no library level documentation comments
    from protobuf: (file:///Users/devoncarew/projects/dart-lang/protobuf/protobuf/lib/protobuf.dart:5:9)
  warning: unresolved doc reference [CodedBufferWritter]
    from protobuf.CodedBufferWriter: (file:///Users/devoncarew/projects/dart-lang/protobuf/protobuf/lib/src/protobuf/coded_buffer_writer.dart:20:7)
  warning: unresolved doc reference [mergeFromProto3JSON]
    from protobuf.GeneratedMessage.mergeFromJson: (file:///Users/devoncarew/projects/dart-lang/protobuf/protobuf/lib/src/protobuf/generated_message.dart:269:8)
  warning: unresolved doc reference [toProto3JSON]
    from protobuf.GeneratedMessage.writeToJson: (file:///Users/devoncarew/projects/dart-lang/protobuf/protobuf/lib/src/protobuf/generated_message.dart:212:10)
  warning: unresolved doc reference [IndexOutOfRangeException]
    from protobuf.FrozenPbList.[]=: (file:///Users/devoncarew/projects/dart-lang/protobuf/protobuf/lib/src/protobuf/pb_list.dart:19:17)
    in documentation inherited from protobuf.PbListBase.[]=: (file:///Users/devoncarew/projects/dart-lang/protobuf/protobuf/lib/src/protobuf/pb_list.dart:378:17)
  warning: unresolved doc reference [IndexOutOfRangeException]
    from protobuf.PbListBase.[]: (file:///Users/devoncarew/projects/dart-lang/protobuf/protobuf/lib/src/protobuf/pb_list.dart:343:14)
  warning: unresolved doc reference [IndexOutOfRangeException]
    from protobuf.PbListBase.[]=: (file:///Users/devoncarew/projects/dart-lang/protobuf/protobuf/lib/src/protobuf/pb_list.dart:378:17)
-
dartdoc 1.0.0 (/Users/devoncarew/projects/dart-lang/dartdoc/bin/dartdoc.dart) failed: Bad state: T extends GeneratedMessage* cannot have parameters
#0      ModelElement.parameters (package:dartdoc/src/model/model_element.dart:980:7)
#1      TypeParameter.referenceChildren (package:dartdoc/src/model/type_parameter.dart:75:23)
#2      DefinedElementType.referenceChildren (package:dartdoc/src/element_type.dart:362:20)
#3      Extension.referenceChildren (package:dartdoc/src/model/extension.dart:127:23)
#4      CommentReferable.referenceBy (package:dartdoc/src/model/comment_referable.dart:112:11)
#5      CommentReferable.referenceBy (package:dartdoc/src/model/comment_referable.dart:122:25)
#6      _getMatchingLinkElementCommentReferable (package:dartdoc/src/markdown_processor.dart:268:31)
#7      getMatchingLinkElement (package:dartdoc/src/markdown_processor.dart:964:16)
#8      _makeLinkNode (package:dartdoc/src/markdown_processor.dart:913:16)
#9      new MarkdownDocument.withElementLinkResolver.linkResolver (package:dartdoc/src/markdown_processor.dart:1062:14)
#10     LinkSyntax._resolveReferenceLink (package:markdown/src/inline_parser.dart:1057:34)
#11     LinkSyntax._tryCreateReferenceLink (package:markdown/src/inline_parser.dart:1085:12)
#12     LinkSyntax.close (package:markdown/src/inline_parser.dart:1028:12)
#13     InlineParser._linkOrImage (package:markdown/src/inline_parser.dart:152:29)
#14     InlineParser.parse (package:markdown/src/inline_parser.dart:108:9)
#15     MarkdownDocument._parseInlineContent (package:dartdoc/src/markdown_processor.dart:1111:67)
#16     MarkdownDocument._parseInlineContent (package:dartdoc/src/markdown_processor.dart:1116:9)
#17     MarkdownDocument.parseMarkdownText (package:dartdoc/src/markdown_processor.dart:1101:5)
#18     Documentation._parseDocumentation (package:dartdoc/src/model/documentation.dart:73:21)
#19     Documentation._renderDocumentation (package:dartdoc/src/model/documentation.dart:48:23)
#20     Documentation.asOneLiner (package:dartdoc/src/model/documentation.dart:40:7)
#21     ModelElement.oneLineDoc (package:dartdoc/src/model/model_element.dart:926:43)
#22     _renderExtension_partial_callable_6 (package:dartdoc/src/generator/templates.aot_renderers_for_html.dart:4690:25)
#23     renderExtension (package:dartdoc/src/generator/templates.aot_renderers_for_html.dart:4226:24)
#24     HtmlAotTemplates.renderExtension (package:dartdoc/src/generator/templates.dart:143:7)
#25     DartdocGeneratorBackend.generateExtension (package:dartdoc/src/generator/dartdoc_generator_backend.dart:171:29)
#26     GeneratorFrontEnd._generateDocs (package:dartdoc/src/generator/generator_frontend.dart:122:29)
#27     GeneratorFrontEnd.generate (package:dartdoc/src/generator/generator_frontend.dart:21:5)
#28     Dartdoc.generateDocsBase (package:dartdoc/dartdoc.dart:213:21)
<asynchronous suspension>
#29     Dartdoc.generateDocs (package:dartdoc/dartdoc.dart:249:28)
<asynchronous suspension>
#30     Dartdoc.executeGuarded.<anonymous closure> (package:dartdoc/dartdoc.dart:512:9)
<asynchronous suspension>
```

**Comment by simolus3** [comment]
This is also happening for one of my packages: https://pub.dev/documentation/moor/latest/log.txt

If it helps, the error occurred after introducing non-function type aliases. Unfortunately I couldn't reproduce it by running `dartdoc` (version 0.42.0 with Dart 2.13.4) locally.

**Comment by jonasfj** [comment]
> Are you seeing this for additional packages?

Grepping logs on pub.dev I suspect it also affects:

 * `complex` version `0.7.2`
 * `convertx` version `0.1.4`
 * `dartlin` version `0.6.0`
 * `dartx` version `0.7.1`
 * `dfunc` version `0.7.2`
 * `fluent_assertions` version `0.4.0`
 * `flutter_form_bloc` version `0.20.5`
 * `flutter_mediator_persistence` version `1.0.1`
 * `flutter_modifiers` version `0.0.1`
 * `flutter_riverpod` version `1.0.0-dev.5`
 * `glass` version `1.0.1`
 * `google_mobile_ads` version `0.13.2`
 * `grizzly_range` version `2.0.9`
 * `ktx` version `1.1.62`
 * `listenable_stream` version `1.1.0`
 * `masamune_core` version `0.6.1+10`
 * `moor_flutter` version `4.0.0`
 * `moor` version `4.4.1`
 * `oagnodes` version `0.0.4`, `0.0.5`, `0.0.6`
 * `protobuf` version `2.0.0`
 * `riverpod` version `1.0.0-dev.5`
 * `rustic` version `0.3.0`
 * `rx_redux` version `2.3.0`
 * `screwdriver` version `2.1.1`
 
 I haven't verified that it's the exact same stack trace, just that they fail with `Bad state` and `cannot have parameters`.
