### ISSUE TITLE
NoSuchMethodError: The getter 'name' was called on null.

### ISSUE THREAD

**Issue by isoos** [dart-lang/dartdoc#2740]
- `dartdoc 1.0.2`
- several packages on pub.dev are affected

To reproduce:
- `git clone https://github.com/glynskyi/ktx`
- `cd ktx`
- `pub global run dartdoc .`

```
Receiver: null
Tried calling: name
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      TypeParameter.referenceChildren (package:dartdoc/src/model/type_parameter.dart:73:17)
#2      DefinedElementType.referenceChildren (package:dartdoc/src/element_type.dart:362:20)
#3      Extension.referenceChildren (package:dartdoc/src/model/extension.dart:127:23)
#4      CommentReferable.referenceBy (package:dartdoc/src/model/comment_referable.dart:112:11)
#5      _getMatchingLinkElementCommentReferable (package:dartdoc/src/markdown_processor.dart:268:31)
#6      getMatchingLinkElement (package:dartdoc/src/markdown_processor.dart:964:16)
#7      _makeLinkNode (package:dartdoc/src/markdown_processor.dart:913:16)
#8      new MarkdownDocument.withElementLinkResolver.linkResolver (package:dartdoc/src/markdown_processor.dart:1062:14)
#9      LinkSyntax._resolveReferenceLink (package:markdown/src/inline_parser.dart:1057:34)
#10     LinkSyntax._tryCreateReferenceLink (package:markdown/src/inline_parser.dart:1085:12)
#11     LinkSyntax.close (package:markdown/src/inline_parser.dart:1028:12)
#12     InlineParser._linkOrImage (package:markdown/src/inline_parser.dart:152:29)
#13     InlineParser.parse (package:markdown/src/inline_parser.dart:108:9)
#14     MarkdownDocument._parseInlineContent (package:dartdoc/src/markdown_processor.dart:1111:67)
#15     MarkdownDocument._parseInlineContent (package:dartdoc/src/markdown_processor.dart:1116:9)
#16     MarkdownDocument.parseMarkdownText (package:dartdoc/src/markdown_processor.dart:1101:5)
#17     Documentation._parseDocumentation (package:dartdoc/src/model/documentation.dart:73:21)
#18     Documentation._renderDocumentation (package:dartdoc/src/model/documentation.dart:48:23)
#19     Documentation.asOneLiner (package:dartdoc/src/model/documentation.dart:40:7)
#20     ModelElement.oneLineDoc (package:dartdoc/src/model/model_element.dart:929:43)
#21     _renderLibrary_partial_extension_7 (package:dartdoc/src/generator/templates.aot_renderers_for_html.dart:6582:25)
#22     renderLibrary (package:dartdoc/src/generator/templates.aot_renderers_for_html.dart:6022:26)
#23     HtmlAotTemplates.renderLibrary (package:dartdoc/src/generator/templates.dart:155:7)
#24     DartdocGeneratorBackend.generateLibrary (package:dartdoc/src/generator/dartdoc_generator_backend.dart:148:29)
#25     GeneratorFrontEnd._generateDocs (package:dartdoc/src/generator/generator_frontend.dart:56:27)
#26     GeneratorFrontEnd.generate (package:dartdoc/src/generator/generator_frontend.dart:21:5)
#27     Dartdoc.generateDocsBase (package:dartdoc/dartdoc.dart:213:21)
```

**Comment by jcollins-g** [comment]
yep, looks like a bug in the new lookup code; it incorrectly assumes all type parameters have a bound type.
