### ISSUE TITLE
unhandled exception: Bad state: typedef [...] = [...] (TypeAliasElementImpl) cannot have parameters

### ISSUE THREAD

**Issue by isoos** [dart-lang/dartdoc#2755]
- dartdoc: 1.0.2
- package archive: https://storage.googleapis.com/pub-packages/packages/moor-4.5.0.tar.gz
- pub.dev logs: https://pub.dev/documentation/moor/latest/log.txt

```
Unhandled exception:
Bad state: typedef BlobColumn = Column<Uint8List?> (TypeAliasElementImpl) cannot have parameters
#0      ModelElement.parameters (package:dartdoc/src/model/model_element.dart:983:7)
#1      Typedef.referenceChildren (package:dartdoc/src/model/typedef.dart:75:31)
#2      CommentReferable.referenceBy (package:dartdoc/src/model/comment_referable.dart:112:11)
#3      _getMatchingLinkElementCommentReferable (package:dartdoc/src/markdown_processor.dart:268:31)
#4      getMatchingLinkElement (package:dartdoc/src/markdown_processor.dart:964:16)
#5      _makeLinkNode (package:dartdoc/src/markdown_processor.dart:913:16)
#6      new MarkdownDocument.withElementLinkResolver.linkResolver (package:dartdoc/src/markdown_processor.dart:1062:14)
#7      LinkSyntax._resolveReferenceLink (package:markdown/src/inline_parser.dart:1057:34)
#8      LinkSyntax._tryCreateReferenceLink (package:markdown/src/inline_parser.dart:1085:12)
#9      LinkSyntax.close (package:markdown/src/inline_parser.dart:1028:12)
#10     InlineParser._linkOrImage (package:markdown/src/inline_parser.dart:152:29)
#11     InlineParser.parse (package:markdown/src/inline_parser.dart:108:9)
#12     MarkdownDocument._parseInlineContent (package:dartdoc/src/markdown_processor.dart:1111:67)
#13     MarkdownDocument._parseInlineContent (package:dartdoc/src/markdown_processor.dart:1116:9)
#14     MarkdownDocument.parseMarkdownText (package:dartdoc/src/markdown_processor.dart:1101:5)
#15     Documentation._parseDocumentation (package:dartdoc/src/model/documentation.dart:73:21)
#16     Documentation._renderDocumentation (package:dartdoc/src/model/documentation.dart:48:23)
#17     Documentation.asOneLiner (package:dartdoc/src/model/documentation.dart:40:7)
#18     ModelElement.oneLineDoc (package:dartdoc/src/model/model_element.dart:929:43)
#19     __renderLibrary_partial_typedef_11_partial_type_2 (package:dartdoc/src/generator/templates.aot_renderers_for_html.dart:7011:25)
#20     _renderLibrary_partial_typedef_11 (package:dartdoc/src/generator/templates.aot_renderers_for_html.dart:6924:18)
#21     renderLibrary (package:dartdoc/src/generator/templates.aot_renderers_for_html.dart:6157:26)
#22     HtmlAotTemplates.renderLibrary (package:dartdoc/src/generator/templates.dart:155:7)
#23     DartdocGeneratorBackend.generateLibrary (package:dartdoc/src/generator/dartdoc_generator_backend.dart:148:29)
#24     GeneratorFrontEnd._generateDocs (package:dartdoc/src/generator/generator_frontend.dart:56:27)
#25     GeneratorFrontEnd.generate (package:dartdoc/src/generator/generator_frontend.dart:21:5)
#26     Dartdoc.generateDocsBase (package:dartdoc/dartdoc.dart:213:21)
<asynchronous suspension>
#27     Dartdoc.generateDocs (package:dartdoc/dartdoc.dart:249:28)
<asynchronous suspension>
#28     main (file:///project/pkg/pub_dartdoc/bin/pub_dartdoc.dart:31:19)
<asynchronous suspension>
```

**Comment by simolus3** [comment]
Very simple repro that crashes `dartdoc`

```dart
/// [List], [String]
typedef T2<X> = List<X>;
```
