### ISSUE TITLE
RangeError (end): Invalid value: Not in inclusive range 7..8: 1

### ISSUE THREAD

**Issue by isoos** [dart-lang/dartdoc#2808]
- seen on `dartdoc` `3.1.0` (SDK: 2.14.1, Flutter 2.5.0), but also on earlier versions
- origin report on pub: https://github.com/dart-lang/pub-dev/issues/5138
- package archive: https://storage.googleapis.com/pub-packages/packages/funvas-0.1.4%2B1.tar.gz

```
RangeError (end): Invalid value: Not in inclusive range 7..8: 1
#0      RangeError.checkValidRange (dart:core/errors.dart:338:9)
#1      _StringBase.substring (dart:core-patch/string_patch.dart:393:27)
#2      CommentReferenceParser._tryParseOperator (package:dartdoc/src/comment_references/parser.dart:219:20)
#3      CommentReferenceParser._parseIdentifier (package:dartdoc/src/comment_references/parser.dart:231:25)
#4      CommentReferenceParser._parseRawCommentReference (package:dartdoc/src/comment_references/parser.dart:114:30)
#5      CommentReferenceParser.parse (package:dartdoc/src/comment_references/parser.dart:85:20)
#6      _ModelCommentReferenceImpl.parsed (package:dartdoc/src/comment_references/model_comment_reference.dart:122:51)
#7      _ModelCommentReferenceImpl._initAllowCache (package:dartdoc/src/comment_references/model_comment_reference.dart:38:27)
#8      _ModelCommentReferenceImpl.allowUnnamedConstructor (package:dartdoc/src/comment_references/model_comment_reference.dart:62:7)
#9      _getMatchingLinkElementCommentReferable (package:dartdoc/src/markdown_processor.dart:197:24)
#10     getMatchingLinkElement (package:dartdoc/src/markdown_processor.dart:261:16)
#11     _makeLinkNode (package:dartdoc/src/markdown_processor.dart:230:16)
#12     new MarkdownDocument.withElementLinkResolver.linkResolver (package:dartdoc/src/markdown_processor.dart:333:14)
#13     LinkSyntax._resolveReferenceLink (package:markdown/src/inline_parser.dart:1057:34)
#14     LinkSyntax._tryCreateReferenceLink (package:markdown/src/inline_parser.dart:1085:12)
#15     LinkSyntax.close (package:markdown/src/inline_parser.dart:1028:12)
#16     InlineParser._linkOrImage (package:markdown/src/inline_parser.dart:152:29)
#17     InlineParser.parse (package:markdown/src/inline_parser.dart:108:9)
#18     MarkdownDocument._parseInlineContent (package:dartdoc/src/markdown_processor.dart:382:67)
#19     MarkdownDocument._parseInlineContent (package:dartdoc/src/markdown_processor.dart:387:9)
#20     MarkdownDocument.parseMarkdownText (package:dartdoc/src/markdown_processor.dart:372:5)
#21     Documentation._parseDocumentation (package:dartdoc/src/model/documentation.dart:73:21)
#22     Documentation._renderDocumentation (package:dartdoc/src/model/documentation.dart:48:23)
#23     Documentation.asOneLiner (package:dartdoc/src/model/documentation.dart:40:7)
#24     ModelElement.oneLineDoc (package:dartdoc/src/model/model_element.dart:932:43)
#25     renderClass (package:dartdoc/src/generator/templates.aot_renderers_for_html.dart:1580:34)
#26     HtmlAotTemplates.renderClass (package:dartdoc/src/generator/templates.dart:128:7)
#27     DartdocGeneratorBackend.generateClass (package:dartdoc/src/generator/dartdoc_generator_backend.dart:157:29)
#28     GeneratorFrontEnd._generateDocs (package:dartdoc/src/generator/generator_frontend.dart:60:29)
#29     GeneratorFrontEnd.generate (package:dartdoc/src/generator/generator_frontend.dart:21:5)
#30     Dartdoc.generateDocsBase (package:dartdoc/dartdoc.dart:214:21)
<asynchronous suspension>
#31     Dartdoc.generateDocs (package:dartdoc/dartdoc.dart:251:24)
```

**Comment by jcollins-g** [comment]
Apparently, the string `Funvas.u` crashes the parser.

**Comment by jcollins-g** [comment]
will publish this Monday next week.

**Comment by isoos** [comment]
thank you!
