### ISSUE TITLE
Dartdoc fails with null check operator used on null value

### ISSUE THREAD

**Issue by bsutton** [dart-lang/dartdoc#2993]
I'm running dartdoc 5.0.1 under dart 2.16.1.

I'm running dartdoc from pub global activate dartdoc.

I'm seeing the following error.
I should note that I have a problem with my tooling in that I'm not running pub get prior to running dartdoc (which 5.0.1 now requires).

In either case we shouldn't be seeing a null check error.

```
Processing: packageStore/public/pi/xbxpsdavuh/pigeon/2.0.3.tar.gz with priority: 0
Failed to generate doc for packageStore/public/pi/xbxpsdavuh/pigeon/2.0.3.tar.gz.
Error Details:
Documenting pigeon...
Initialized dartdoc with 48 libraries
Generating docs for library objc_generator from file:///tmp/1fc6e01a-39ad-48c3-b48d-d6c0b90711fe/lib/objc_generator.dart...
../…/lib/objc_generator.dart:1
Generating docs for library ast_generator from file:///tmp/1fc6e01a-39ad-48c3-b48d-d6c0b90711fe/lib/ast_generator.dart...
../…/lib/ast_generator.dart:1
Generating docs for library functional from file:///tmp/1fc6e01a-39ad-48c3-b48d-d6c0b90711fe/lib/functional.dart...
../…/lib/functional.dart:1
Generating docs for library java_generator from file:///tmp/1fc6e01a-39ad-48c3-b48d-d6c0b90711fe/lib/java_generator.dart...
../…/lib/java_generator.dart:1
Generating docs for library pigeon from file:///tmp/1fc6e01a-39ad-48c3-b48d-d6c0b90711fe/lib/pigeon.dart...
../…/lib/pigeon.dart:1
Generating docs for library dart_generator from file:///tmp/1fc6e01a-39ad-48c3-b48d-d6c0b90711fe/lib/dart_generator.dart...
../…/lib/dart_generator.dart:1
Generating docs for library pigeon_lib from file:///tmp/1fc6e01a-39ad-48c3-b48d-d6c0b90711fe/lib/pigeon_lib.dart...
../…/lib/pigeon_lib.dart:1

  warning: unresolved doc reference [forEach]
from functional.enumerate:
../…/lib/functional.dart:17
  warning: unresolved doc reference [map]
from functional.indexMap:
../…/lib/functional.dart:7
  warning: unresolved doc reference [map]
from functional.map2:
../…/lib/functional.dart:27
  warning: unresolved doc reference [map]
from functional.map3:
../…/lib/functional.dart:41

dartdoc 5.0.1 (/home/bsutton/.pub-cache/global_packages/dartdoc/bin/dartdoc.dart-2.16.1.snapshot) failed: Null check operator used on a null value
#0      Prefix.associatedLibrary package:dartdoc/…/model/prefix.dart:30
#1      Prefix.canonicalModelElement package:dartdoc/…/model/prefix.dart:33
#2      Prefix.href package:dartdoc/…/model/prefix.dart:49
#3      _makeLinkNode package:dartdoc/src/markdown_processor.dart:237
```

**Comment by bsutton** [comment]
Just an update.
If I run pub get before running dartdoc, dartdoc does run successfully to completion.

**Comment by bwilkerson** [comment]
I'm marking this a P2 because there's a work-around, but the tool ought to not crash even when `pub` hasn't been run, so this should still be addressed.

**Comment by srawlins** [comment]
Sorry we didnt get to this; closing as stale but please re-open if you can reproduce with a recent dartdoc.
