### ISSUE TITLE
DartDoc 5.1.0 crashing on Flutter Docs

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/dartdoc#3039]
I tried to bump Flutter's use of dartdoc to 5.1.0 in https://github.com/flutter/flutter/pull/104010, but its reliably crashing on CI: https://cirrus-ci.com/task/6006578632458240

```
dartdoc:stdout: Generating docs for library webdriver.sync_core from package:webdriver/sync_core.dart...
dartdoc:stderr:
dartdoc:stderr: dartdoc 5.1.0 (/root/.pub-cache/global_packages/dartdoc/bin/dartdoc.dart-2.18.0-124.0.dev.snapshot) failed: FileSystemException(path=/root/.pub-cache/hosted/pub.dartlang.org/dartdoc-5.1.0/lib/resources/docs.dart.js; message=Cannot open file)
dartdoc:stderr: #0      _PhysicalFile.readAsBytesSync (package:analyzer/file_system/physical_file_system.dart:148:7)
dartdoc:stderr: #1      HtmlGeneratorBackend._copyResources (package:dartdoc/src/generator/html_generator.dart:70:46)
dartdoc:stderr: <asynchronous suspension>
dartdoc:stderr: #2      HtmlGeneratorBackend.generateAdditionalFiles (package:dartdoc/src/generator/html_generator.dart:49:5)
dartdoc:stderr: <asynchronous suspension>
dartdoc:stderr: #3      GeneratorFrontEnd.generate (package:dartdoc/src/generator/generator_frontend.dart:25:5)
dartdoc:stderr: <asynchronous suspension>
dartdoc:stderr: #4      Dartdoc.generateDocsBase (package:dartdoc/src/dartdoc.dart:181:5)
dartdoc:stderr: <asynchronous suspension>
dartdoc:stderr: #5      Dartdoc.generateDocs (package:dartdoc/src/dartdoc.dart:223:24)
dartdoc:stderr: <asynchronous suspension>
dartdoc:stderr: #6      Dartdoc.executeGuarded.<anonymous closure> (package:dartdoc/src/dartdoc.dart:261:9)
dartdoc:stderr: <asynchronous suspension>
```

**Comment by srawlins** [comment]
Thanks for testing!

**Comment by srawlins** [comment]
The problem is in the `.pubignore`.

**Comment by goderbauer** [comment]
Which `.pubignore` is that? Something we can fix in Flutter?

**Comment by srawlins** [comment]
Nope, mine. That missing file is in the dartdoc repo, but was not published in 5.1.0.

**Comment by devoncarew** [comment]
I see the fix PR; you could also consider retracting `5.1.0` (un-publishing it).

**Comment by srawlins** [comment]
Hmm, I think it should be fine to just bump the version.

**Comment by goderbauer** [comment]
Thanks for the quick fix!

**Comment by ikurek** [comment]
@srawlins When can we expect the fix to land on pub.dev?

**Comment by goderbauer** [comment]
Looks like 5.1.1 is still failing for flutter with a smiliar, but slightly different exception: https://github.com/flutter/flutter/pull/104094/checks?check_run_id=6493272089

```
dartdoc:stdout: Generating docs for library webdriver.io from package:webdriver/io.dart...
dartdoc:stderr:
dartdoc:stderr: dartdoc 5.1.1 (/b/s/w/ir/x/w/.pub-cache/global_packages/dartdoc/bin/dartdoc.dart-2.18.0-128.0.dev.snapshot) failed: FileSystemException(path=/b/s/w/ir/x/w/.pub-cache/hosted/pub.dartlang.org/dartdoc-5.1.1/lib/resources/docs.dart.js.map; message=Cannot open file)
dartdoc:stderr: #0      _PhysicalFile.readAsBytesSync (package:analyzer/file_system/physical_file_system.dart:148:7)
dartdoc:stderr: #1      HtmlGeneratorBackend._copyResources (package:dartdoc/src/generator/html_generator.dart:70:46)
dartdoc:stderr: <asynchronous suspension>
dartdoc:stderr: #2      HtmlGeneratorBackend.generateAdditionalFiles (package:dartdoc/src/generator/html_generator.dart:49:5)
dartdoc:stderr: <asynchronous suspension>
dartdoc:stderr: #3      GeneratorFrontEnd.generate (package:dartdoc/src/generator/generator_frontend.dart:25:5)
dartdoc:stderr: <asynchronous suspension>
dartdoc:stderr: #4      Dartdoc.generateDocsBase (package:dartdoc/src/dartdoc.dart:181:5)
dartdoc:stderr: <asynchronous suspension>
dartdoc:stderr: #5      Dartdoc.generateDocs (package:dartdoc/src/dartdoc.dart:223:24)
dartdoc:stderr: <asynchronous suspension>
dartdoc:stderr: #6      Dartdoc.executeGuarded.<anonymous closure> (package:dartdoc/src/dartdoc.dart:261:9)
dartdoc:stderr: <asynchronous suspension>
```
