### ISSUE TITLE
5.1.0 release is broken

### ISSUE THREAD

**Issue by simolus3** [dart-lang/dartdoc#3041]
The 5.1.0 release on pub.dev does not contain the `lib/resources/docs.dart.js` file, causing this exception when documenting anything with it:

```
dartdoc 5.1.0 (/home/simon/programming/drift/docs/.dart_tool/pub/bin/dartdoc/dartdoc.dart-2.17.0.snapshot) failed: FileSystemException(path=/home/simon/.pub-cache/hosted/pub.dartlang.org/dartdoc-5.1.0/lib/resources/docs.dart.js; message=Cannot open file)
#0      _PhysicalFile.readAsBytesSync (package:analyzer/file_system/physical_file_system.dart:148:7)
#1      HtmlGeneratorBackend._copyResources (package:dartdoc/src/generator/html_generator.dart:70:46)
<asynchronous suspension>
#2      HtmlGeneratorBackend.generateAdditionalFiles (package:dartdoc/src/generator/html_generator.dart:49:5)
<asynchronous suspension>
#3      GeneratorFrontEnd.generate (package:dartdoc/src/generator/generator_frontend.dart:25:5)
<asynchronous suspension>
#4      Dartdoc.generateDocsBase (package:dartdoc/src/dartdoc.dart:181:5)
<asynchronous suspension>
#5      Dartdoc.generateDocs (package:dartdoc/src/dartdoc.dart:223:24)
<asynchronous suspension>
#6      Dartdoc.executeGuarded.<anonymous closure> (package:dartdoc/src/dartdoc.dart:261:9)
<asynchronous suspension>
```

**Comment by jxstxn1** [comment]
I can reproduce this.
## How to reproduce:
 - Go to a dart project or create a new one with `dart create your_project`
 - Install the Docs package if you don't have it already with `dart pub global activate dartdoc`
 - Try to generate docs by using: `dartdoc`

**Comment by dellgreen** [comment]
See: #3040
