### ISSUE TITLE
UnimplementedError: Unknown type MultiplyDefinedElementImpl

### ISSUE THREAD

**Issue by isoos** [dart-lang/dartdoc#3073]
Happened while generating docs for `slide_drawer 1.0.3`:
https://pub.dev/packages/slide_drawer/versions/1.0.3.tar.gz

```
Generating docs for library slide_drawer from package:slide_drawer/slide_drawer.dart...
  warning: slide_drawer has no library level documentation comments
    from slide_drawer: (file:///home/isoos/work/google/pub-dev/x/lib/slide_drawer.dart:1:9)
  warning: unresolved doc reference [start]
    from slide_drawer.SlideDrawerContainer.alignment: (file:///home/isoos/work/google/pub-dev/x/lib/src/container.dart:33:31)
    in documentation inherited from slide_drawer.SlideDrawerContainer.alignment: (file:///home/isoos/work/google/pub-dev/x/lib/src/container.dart:33:31)
  warning: unresolved doc reference [center]
    from slide_drawer.SlideDrawerContainer.alignment: (file:///home/isoos/work/google/pub-dev/x/lib/src/container.dart:33:31)
    in documentation inherited from slide_drawer.SlideDrawerContainer.alignment: (file:///home/isoos/work/google/pub-dev/x/lib/src/container.dart:33:31)
  warning: unresolved doc reference [background]
    from slide_drawer.SlideDrawerContainer.backgroundGradient: (file:///home/isoos/work/google/pub-dev/x/lib/src/container.dart:17:19)
    in documentation inherited from slide_drawer.SlideDrawerContainer.backgroundGradient: (file:///home/isoos/work/google/pub-dev/x/lib/src/container.dart:17:19)
  warning: unresolved doc reference [start]
    from slide_drawer.SlideDrawer.alignment: (file:///home/isoos/work/google/pub-dev/x/lib/src/drawer.dart:61:31)
    in documentation inherited from slide_drawer.SlideDrawer.alignment: (file:///home/isoos/work/google/pub-dev/x/lib/src/drawer.dart:61:31)
  warning: unresolved doc reference [center]
    from slide_drawer.SlideDrawer.alignment: (file:///home/isoos/work/google/pub-dev/x/lib/src/drawer.dart:61:31)
    in documentation inherited from slide_drawer.SlideDrawer.alignment: (file:///home/isoos/work/google/pub-dev/x/lib/src/drawer.dart:61:31)
  warning: unresolved doc reference [background]
    from slide_drawer.SlideDrawer.backgroundGradient: (file:///home/isoos/work/google/pub-dev/x/lib/src/drawer.dart:13:19)
    in documentation inherited from slide_drawer.SlideDrawer.backgroundGradient: (file:///home/isoos/work/google/pub-dev/x/lib/src/drawer.dart:13:19)
  warning: unresolved doc reference [true]
    from slide_drawer.SlideDrawer.isRotate: (file:///home/isoos/work/google/pub-dev/x/lib/src/drawer.dart:71:14)
    in documentation inherited from slide_drawer.SlideDrawer.isRotate: (file:///home/isoos/work/google/pub-dev/x/lib/src/drawer.dart:71:14)
Unhandled exception:
UnimplementedError: Unknown type MultiplyDefinedElementImpl
#0      ModelElement._fromParameters (package:dartdoc/src/model/model_element.dart:386:5)
#1      new ModelElement._from (package:dartdoc/src/model/model_element.dart:269:40)
#2      new ModelElement._fromElement (package:dartdoc/src/model/model_element.dart:151:25)
#3      ModelElementBuilderImpl.fromElement (package:dartdoc/src/model/model_element.dart:72:20)
#4      CommentReferable._lookupViaScope (package:dartdoc/src/model/comment_referable.dart:150:31)
#5      CommentReferable.referenceBy (package:dartdoc/src/model/comment_referable.dart:111:22)
#6      CommentReferable.referenceBy (package:dartdoc/src/model/comment_referable.dart:126:29)
#7      CommentReferable.referenceBy (package:dartdoc/src/model/comment_referable.dart:126:29)
#8      _getMatchingLinkElementCommentReferable (package:dartdoc/src/markdown_processor.dart:223:31)
#9      getMatchingLinkElement (package:dartdoc/src/markdown_processor.dart:264:16)
#10     _makeLinkNode (package:dartdoc/src/markdown_processor.dart:231:16)
#11     new MarkdownDocument.withElementLinkResolver.linkResolver (package:dartdoc/src/markdown_processor.dart:338:14)
#12     LinkSyntax._resolveReferenceLink (package:markdown/src/inline_parser.dart:1058:34)
#13     LinkSyntax._tryCreateReferenceLink (package:markdown/src/inline_parser.dart:1086:12)
#14     LinkSyntax.close (package:markdown/src/inline_parser.dart:1029:12)
#15     InlineParser._linkOrImage (package:markdown/src/inline_parser.dart:150:29)
#16     InlineParser.parse (package:markdown/src/inline_parser.dart:106:9)
```

**Comment by bwilkerson** [comment]
Instances of `MultiplyDefinedElementImpl` (should) only occur when a name used in a library is imported from multiple libraries. Does the code that dartdoc was being run over have any analysis errors?

Which version of Flutter were you using?

**Comment by srawlins** [comment]
The package has 41 analysis errors, including many ambiguous_import.

I don't think that changes how/whether we should fix though.

**Comment by jcollins-g** [comment]
I know it used to be that dartdoc was not happy at all running over code with certain kinds of analysis errors.  Maybe the fix here is to explicitly say, this package has `ambiguous_import` errors and can not be documented before bailing out?
