### ISSUE TITLE
LateInitializationError: Field 'enclosingCombo' has not been initialized.

### ISSUE THREAD

**Issue by Tkko** [dart-lang/dartdoc#3210]
When I run `dart doc .` in my [project](https://pub.dev/packages/pinput) it works fine but `flutter pub global run dartdoc:dartdoc` is failing on my local machine and on top of that  [pub.dev](https://pub.dev/packages/pinput/score) scoring system is also failing

**dart --version:**
`Dart SDK version: 2.18.2 (stable) (Tue Sep 27 13:24:11 2022 +0200) on "macos_arm64"`

**The exception:**
```
exitCode: 255
stdout: [2022-10-07T08:19:56.540247] Starting...
Documenting pinput...
Initialized dartdoc with 622 libraries
Generating docs for library pinput from package:pinput/pinput.dart...

stderr: Unhandled exception:
LateInitializationError: Field 'enclosingCombo' has not been initialized.
#0      Accessor.enclosingCombo (package:dartdoc/src/model/accessor.dart)
#1      CommentReferable._lookupViaScope (package:dartdoc/src/model/comment_refe[...]
#2      CommentReferable.referenceBy (package:dartdoc/src/model/comment_referabl[...]
#3      CommentReferable.referenceBy (package:dartdoc/src/model/comment_referabl[...]
#4      CommentReferable.referenceBy (package:dartdoc/src/model/comment_referabl[...]
#5      _getMatchingLinkElement (package:dartdoc/src/markdown_processor.dart:226:30)
#6      getMatchingLinkElement (package:dartdoc/src/markdown_processor.dart:238:16)
#7      MarkdownDocument._makeLinkNode (package:dartdoc/src/markdown_processor.d[...]
#8      new MarkdownDocument.withElementLinkResolver.<anonymous closure> (packag[...]
#9      LinkSyntax._resolveReferenceLink (package:markdown/src/inline_syntaxes/l[...]
#10     LinkSyntax._tryCreateReferenceLink (package:markdown/src/inline_syntaxes[...]
#11     LinkSyntax.close (package:markdown/src/inline_syntaxes/link_syntax.dart:40:14)
#12     InlineParser._linkOrImage (package:markdown/src/inline_parser.dart:158:31)
#13     InlineParser.parse (package:markdown/src/inline_parser.dart:114:9)
#14     MarkdownDocument._parseInlineContent (package:dartdoc/src/markdown_proce[...]
#15     MarkdownDocument._parseInlineContent (package:dartdoc/src/markdown_proce[...]
#16     MarkdownDocument.parseMarkdownText (package:dartdoc/src/markdown_process[...]
#17     Documentation._parseDocumentation (package:dartdoc/src/model/documentati[...]
#18     Documentation._renderDocumentation (package:dartdoc/src/model/documentat[...]
#19     Documentation.asOneLiner (package:dartdoc/src/model/documentation.dart:54:5)
#20     ModelElement.oneLineDoc (package:dartdoc/src/model/model_element.dart:816:49)
#21     GetterSetterCombo.oneLineDoc.<anonymous closure> (package:dartdoc/src/mo[...]
#22     GetterSetterCombo.oneLineDoc (package:dartdoc/src/model/getter_setter_co[...]
#23     GetterSetterCombo.oneLineDoc (package:dartdoc/src/model/getter_setter_combo.dart)
#24     _deduplicated_lib_templates_html__property_html (package:dartdoc/src/gen[...]
#25     _renderClass_partial_property_10 (package:dartdoc/src/generator/template[...]
#26     renderClass (package:dartdoc/src/generator/templates.aot_renderers_for_h[...]
#27     HtmlAotTemplates.renderClass (package:dartdoc/src/generator/templates.da[...]
#28     GeneratorBackendBase.generateClass (package:dartdoc/src/generator/genera[...]
#29     GeneratorFrontEnd._generateDocs (package:dartdoc/src/generator/generator[...]
#30     GeneratorFrontEnd.generate (package:dartdoc/src/generator/generator_fron[...]
#31     Dartdoc.generateDocsBase (package:dartdoc/src/dartdoc.dart:178:21)
<asynchronous suspension>
#32     Dartdoc.generateDocs (package:dartdoc/src/dartdoc.dart:220:24)
<asynchronous suspension>
#33     main (file:///project/pkg/pub_dartdoc/bin/pub_dartdoc.dart:32:19)
<asynchronous suspension>

```

**Comment by srawlins** [comment]
Thanks for the bug report! I think I've seen this once myself in our unit tests (but not consistently?!). It's a priority bug.

**Comment by srawlins** [comment]
Can you note the version of dart you're using? `dart --version` I guess.

**Comment by Tkko** [comment]
> Can you note the version of dart you're using? `dart --version` I guess.

Dart SDK version: 2.18.2 (stable)

**Comment by srawlins** [comment]
The root cause here is that `_defaultSmsCodeMatcher` is _referenced_ in a public doc comment, but is not a documented element (it is implementation-private).
