### ISSUE TITLE
Dartdoc crashes with macros

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/dartdoc#3653]
Repro instructions:

Check out this repo/branch https://github.com/jakemac53/macros_example/tree/dartdoc-failure

Using a custom built recent SDK:

- Run `dart pub upgrade`. You may want to delete the `pubspec_overrides.yaml` file first, or change the paths in it to point at your own local SDK.
- Run `dart --enable-experiment=macros doc .`

You will observe two issues:

- It won't exit properly, cc @scheglov should be able to comment on how to shut down the analysis context
- It will crash, with an exception like the following:

```
Bad state: The target must be a declaration, not an augmentation.
#0      InterfaceElementExtension.augmentedOfDeclaration (package:analyzer/src/dart/element/extensions.dart:142:7)
dart-lang/sdk#1      ClassHierarchy._getHierarchy (package:analyzer/src/dart/element/class_hierarchy.dart:38:31)
dart-lang/sdk#2      ClassHierarchy.implementedInterfaces (package:analyzer/src/dart/element/class_hierarchy.dart:22:12)
dart-lang/sdk#3      InterfaceElementImpl.allSupertypes (package:analyzer/src/dart/element/element.dart:3456:43)
dart-lang/sdk#4      Method.overriddenElement (package:dartdoc/src/model/method.dart:116:26)
dart-lang/sdk#5      DocumentationComment.documentationFrom.<anonymous closure> (package:dartdoc/src/model/documentation_comment.dart:58:46)
dart-lang/sdk#6      DocumentationComment.documentationFrom (package:dartdoc/src/model/documentation_comment.dart:65:8)
dart-lang/sdk#7      PackageGraph._precacheLocalDocs (package:dartdoc/src/model/package_graph.dart:178:31)
dart-lang/sdk#8      PackageGraph.initializePackageGraph (package:dartdoc/src/model/package_graph.dart:132:23)
dart-lang/sdk#9      PubPackageBuilder.buildPackageGraph (package:dartdoc/src/model/package_builder.dart:90:20)
<asynchronous suspension>
dart-lang/sdk#10     Dartdoc.generateDocsBase (package:dartdoc/src/dartdoc.dart:189:24)
<asynchronous suspension>
dart-lang/sdk#11     Dartdoc.generateDocs (package:dartdoc/src/dartdoc.dart:233:24)
<asynchronous suspension>
dart-lang/sdk#12     Dartdoc.executeGuarded.<anonymous closure> (package:dartdoc/src/dartdoc.dart:265:9)
<asynchronous suspension>
```

Note that I was running this to see if I could see the generated toJson/fromJson members in the docs.

cc @srawlins

**Comment by scheglov** [comment]
To avoid hanging you need to invoke `AnalysisContextCollectionImpl.dispose()`, this will stop started macro execution isolate.

**Comment by scheglov** [comment]
You see the exception because now not every `ClassElement` is the "owner" of the class hierarchy. Only declarations are, but not augmentations. When you have a `ClassElement`, you need to go to the declaration with `classElement.augmented.declaration`.

**Comment by srawlins** [comment]
Sorry, just looking at this now. Calling `.dispose` now gives me a different exception, something from the macro code, @jakemac53. This is with an SDK built this morning, and analyzer 6.4.1:

```none
Bad state: Expected a bool but found a DataKind.oneByteString
#0      ByteDataDeserializer.expectBool (package:_fe_analyzer_shared/src/macros/executor/serialization.dart:466:7)
#1      DeserializerExtensions._expectFunctionTypeAnnotation (package:_fe_analyzer_shared/src/macros/executor/serialization_extensions.dart:137:21)
#2      DeserializerExtensions.expectRemoteInstance (package:_fe_analyzer_shared/src/macros/executor/serialization_extensions.dart:52:28)
#3      DeserializerExtensions._expectClassDeclaration (package:_fe_analyzer_shared/src/macros/executor/serialization_extensions.dart:291:21)
#4      DeserializerExtensions.expectRemoteInstance (package:_fe_analyzer_shared/src/macros/executor/serialization_extensions.dart:32:28)
#5      RemoteInstance.deserialize (package:_fe_analyzer_shared/src/macros/executor/remote_instance.dart:46:34)
#6      new ExecutePhaseRequest.deserialize (package:_fe_analyzer_shared/src/macros/executor/protocol.dart:278:33)
#7      new ExecuteDeclarationsPhaseRequest.deserialize (package:_fe_analyzer_shared/src/macros/executor/protocol.dart:317:15)
#8      MacroExpansionClient._handleMessage.<anonymous closure> (package:_fe_analyzer_shared/src/macros/executor/client.dart:134:19)
#9      _rootRun (dart:async/zone.dart:1399:13)
#10     _CustomZone.run (dart:async/zone.dart:1301:19)
#11     withRemoteInstanceZone (package:_fe_analyzer_shared/src/macros/executor/remote_instance.dart:173:15)
#12     MacroExpansionClient._handleMessage (package:_fe_analyzer_shared/src/macros/executor/client.dart:118:11)
#13     new MacroExpansionClient._.<anonymous closure> (package:_fe_analyzer_shared/src/macros/executor/client.dart:37:39)
#14     _rootRunUnary (dart:async/zone.dart:1415:13)
#15     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#20     _StreamController._add (dart:async/stream_controller.dart:658:7)
#21     _StreamController.add (dart:async/stream_controller.dart:606:5)
#22     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by jakemac53** [comment]
> Sorry, just looking at this now. Calling `.dispose` now gives me a different exception, something from the macro code, @jakemac53. This is with an SDK built this morning, and analyzer 6.4.1:

This is a version mismatch between your local analyzer (or actually, _fe_analyzer_shared) and what your SDK was compiled with.

**Comment by srawlins** [comment]
ROFL. What's the solution here? Is there a design doc for how analyzer releases will align with SDK releases? Dartdoc can pin such analyzer versions in deps.

**Comment by jakemac53** [comment]
> ROFL. What's the solution here? Is there a design doc for how analyzer releases will align with SDK releases? Dartdoc can pin such analyzer versions in deps.

The long term solution is to wait for `package:macros` :). These APIs are moving to a `dart:_macros` library will be will be exported by `package:macros`, so multiple versions won't be possible.

You could write a test today by pinning dependencies to a dev version (using a git dependencies).

**Comment by srawlins** [comment]
OK that sounds viable. Thanks! I can get dartdoc to get further in the process. Next is that we try to read the source from disk for a macro. I'll have to add support for understanding to not do that.

```none
dartdoc 8.0.6-wip (/Users/srawlins/code/dart-dartdoc/bin/dartdoc.dart) failed: PathNotFoundException(path=/Users/srawlins/code/dart-macros_example/lib/user.macro.dart; message=Cannot open file)
#0      _PhysicalFile.readAsStringSync (package:analyzer/file_system/physical_file_system.dart:165:7)
#1      getFileContentsFor (package:dartdoc/src/model_utils.dart:88:55)
#2      ModelNode.sourceCode (package:dartdoc/src/model/model_node.dart:52:12)
```
