### ISSUE TITLE
error running dartdoc

### ISSUE THREAD

**Issue by d2m** [dart-lang/dartdoc#38]
is this working for you, because running dartdoc on itself or other packages gets me an error

Dart VM version: 1.8.3 (Mon Dec  1 08:39:04 2014) on "linux_ia32"
```
$ pub run dartdoc
parsing /.../dartdoc/lib/dartdoc.dart...
generating docs/dartdoc_package.html
generating docs/dartdoc.html
Unhandled exception:
type 'MappedListIterable' is not a subtype of type 'List<Parameter>' of 'params'.
#0      HtmlGeneratorHelper.printParams (package:dartdoc/src/generator.dart:501:38)
#1      ModelElement.createLinkedSummary (package:dartdoc/src/model.dart:125:39)
#2      HtmlGenerator.createToc (package:dartdoc/src/generator.dart:184:65)
#3      generateClass (package:dartdoc/src/generator.dart:236:14)
#4      List.forEach (dart:core-patch/growable_array.dart:254)
#5      HtmlGenerator.generateLibrary (package:dartdoc/src/generator.dart:161:18)
#6      HtmlGenerator.generate.<anonymous closure> (package:dartdoc/src/generator.dart:37:55)
#7      List.forEach (dart:core-patch/growable_array.dart:254)
#8      HtmlGenerator.generate (package:dartdoc/src/generator.dart:37:30)
#9      DartDoc.generateDocs (package:dartdoc/dartdoc.dart:60:23)
#10     main (http://localhost:35193/dartdoc.dart:26:62)
#11     _startIsolate (dart:isolate-patch/isolate_patch.dart:237)
#12     _startMainIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:192)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:130)
```

Dart VM version: 1.9.0-dev.2.2 (Sun Dec 21 11:39:18 2014) on "linux_ia32"
```
$ pub run dartdoc
parsing /.../dartdoc/lib/dartdoc.dart...
generating docs/dartdoc_package.html
generating docs/dartdoc.html
Unhandled exception:
type 'MappedListIterable' is not a subtype of type 'List<Parameter>' of 'params'.
#0      HtmlGeneratorHelper.printParams (package:dartdoc/src/generator.dart:501:38)
#1      ModelElement.createLinkedSummary (package:dartdoc/src/model.dart:125:39)
#2      HtmlGenerator.createToc (package:dartdoc/src/generator.dart:184:65)
#3      generateClass (package:dartdoc/src/generator.dart:236:14)
#4      List.forEach (dart:core-patch/growable_array.dart:219)
#5      HtmlGenerator.generateLibrary (package:dartdoc/src/generator.dart:161:18)
#6      HtmlGenerator.generate.<anonymous closure> (package:dartdoc/src/generator.dart:37:55)
#7      List.forEach (dart:core-patch/growable_array.dart:219)
#8      HtmlGenerator.generate (package:dartdoc/src/generator.dart:37:30)
#9      DartDoc.generateDocs (package:dartdoc/dartdoc.dart:60:23)
#10     main (http://localhost:51146/dartdoc.dart:26:62)
#11     _startMainIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:203)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:141)
```

**Comment by sethladd** [comment]
Thanks for the report! We should probably have a test for this... running dartdoc on itself seems like a reasonable goal :)

**Comment by keertip** [comment]
Fixed exceptions. Unfortunately, using pub run vs. the VM exhibits different behavior when running dartdoc. So even with the fix, running dartdoc with pub run does not work. Works running it with the VM.

**Comment by d2m** [comment]
Thanks for the fix. Want to say, that ```DART_SDK``` needs to be set or ```--dart-sdk``` passed as an option if running with the VM.

**Comment by sethladd** [comment]
@keertip do you know why dartdoc requires an explicitly set location for the SDK?

**Comment by keertip** [comment]
dartdoc does not need location of SDK. Maybe the DART_SDK is used here to set path to the vm?

**Comment by devoncarew** [comment]
The analyzer library we're using needs to be able to locate the `dart:` sources.

**Comment by keertip** [comment]
Yes, that is true, but it works without having to specify where the sdk is located. It will still generate docs for package.

**Comment by sethladd** [comment]
How do I use --dart-sdk? Added it to the command line throws an error:

```
sethladd@sethladd-macbookair ~/Code/dart-uuid (master)$ dart ../dartdoc/bin/dartdoc.dart --dart-sdk=~/homebrew/Cellar/dart/1.8.3/libexec/
Unhandled exception:
FormatException: Could not find an option named "dart-sdk".
```

**Comment by keertip** [comment]
Currently there is no option for passing the sdk location. Just run

dart ../dartdoc/bin/dartdoc.dart
