### ISSUE TITLE
failure rolling into the dart sdk repo

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#3808]
I'm seeing a failure documenting the sdk when rolling head into the dart sdk repo:

```
dartdoc 8.0.10 (/b/s/w/ir/cache/builder/sdk/dartdev) failed: UnimplementedError: Unknown type FieldElementImpl
#0      ModelElement._constructFromElementDeclaration (package:dartdoc/src/model/model_element.dart:311:12)
#1      new ModelElement.for_ (package:dartdoc/src/model/model_element.dart:229:40)
#2      Nameable.getModelFor (package:dartdoc/src/model/nameable.dart:54:20)
#3      PackageGraph.findCanonicalModelElementFor (package:dartdoc/src/model/package_graph.dart:772:16)
#4      ContainerMember.referenceGrandparentOverrides (package:dartdoc/src/model/container_member.dart:64:23)
#5      CommentReferable.referenceBy (package:dartdoc/src/model/comment_referable.dart:81:28)
#6      _getMatchingLinkElement (package:dartdoc/src/markdown_processor.dart:176:15)
#7      getMatchingLinkElement (package:dartdoc/src/markdown_processor.dart:187:16)
#8      MarkdownDocument._makeLinkNode (package:dartdoc/src/markdown_processor.dart:313:18)
#9      new MarkdownDocument.withElementLinkResolver.<anonymous closure> (package:dartdoc/src/markdown_processor.dart:267:51)
#10     LinkSyntax._resolveReferenceLink (package:markdown/src/inline_syntaxes/link_syntax.dart:137:36)
#11     LinkSyntax._tryCreateReferenceLink (package:markdown/src/inline_syntaxes/link_syntax.dart:177:18)
#12     LinkSyntax.close (package:markdown/src/inline_syntaxes/link_syntax.dart:103:12)
#13     InlineParser._linkOrImage (package:markdown/src/inline_parser.dart:150:32)
#14     InlineParser.parse (package:markdown/src/inline_parser.dart:106:9)
#15     MarkdownDocument._parseInlineContent (package:dartdoc/src/markdown_processor.dart:298:67)
#16     MarkdownDocument._parseInlineContent (package:dartdoc/src/markdown_processor.dart:303:9)
#17     MarkdownDocument.parseMarkdownText (package:dartdoc/src/markdown_processor.dart:288:5)
#18     Documentation._parseDocumentation (package:dartdoc/src/model/documentation.dart:83:21)
#19     Documentation._renderDocumentation (package:dartdoc/src/model/documentation.dart:64:23)
#20     Documentation.asHtml (package:dartdoc/src/model/documentation.dart:49:5)
#21     DocumentationComment.documentationAsHtml (package:dartdoc/src/model/documentation_comment.dart:62:49)
#22     DocumentationComment.documentationAsHtml (package:dartdoc/src/model/documentation_comment.dart)
#23     EmptyGenerator.generate (package:dartdoc/src/generator/empty_generator.dart:27:25)
#24     Dartdoc.generateDocsBase (package:dartdoc/src/dartdoc.dart:203:21)
<asynchronous suspension>
#25     Dartdoc.generateDocs (package:dartdoc/src/dartdoc.dart:241:24)
<asynchronous suspension>
#26     Dartdoc.executeGuarded.<anonymous closure> (package:dartdoc/src/dartdoc.dart:273:9)
<asynchronous suspension>
```

**Comment by srawlins** [comment]
Thanks for catching @devoncarew ! What's the command I can use in the SDK to reproduce?

**Comment by devoncarew** [comment]
Here's the link to the failure (which may not live too long): https://ci.chromium.org/ui/p/dart/builders/try/pkg-linux-release-try/91534/overview

After you rev the dartdoc dep and rebuild the sdk, you want to run:

`./out/ReleaseX64/dart-sdk/bin/dart doc --sdk-docs --dry-run --verbose`

**Comment by srawlins** [comment]
OK I reproduced this with a unit test. Thanks!
