### ISSUE TITLE
dartdoc doesn't "just run"

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#42]
To repro:

Clone dartdoc
git clone git@github.com:Daegalus/dart-uuid.git
cd dart-uuid
dart ../dartdoc/bin/dartdoc.dart

Error:

```
sethladd@sethladd-macbookair ~/Code/dart-uuid (master)$ dart ../dartdoc/bin/dartdoc.dart 
parsing /Users/sethladd/Code/dart-uuid/lib/aes.dart...
Unhandled exception:
AnalysisException: <rethrow>
Caused by Could not resolve dart:core
#0      AnalysisTask._safelyPerform (package:analyzer/src/generated/engine.dart:6762:7)
#1      AnalysisTask.perform (package:analyzer/src/generated/engine.dart:6727:21)
#2      AnalysisContextImpl._cacheDartResolutionData (package:analyzer/src/generated/engine.dart:2414:86)
#3      AnalysisContextImpl._getDartResolutionData (package:analyzer/src/generated/engine.dart:3046:41)
#4      AnalysisContextImpl._getDartResolutionData2 (package:analyzer/src/generated/engine.dart:3077:36)
#5      AnalysisContextImpl.computeLibraryElement (package:analyzer/src/generated/engine.dart:1192:81)
#6      DartDoc.parseLibraries.<anonymous closure> (package:dartdoc/dartdoc.dart:90:63)
#7      List.forEach (dart:core-patch/growable_array.dart:254)
#8      DartDoc.parseLibraries (package:dartdoc/dartdoc.dart:86:18)
#9      DartDoc.generateDocs (package:dartdoc/dartdoc.dart:42:31)
#10     main (file:///Users/sethladd/Code/dartdoc/bin/dartdoc.dart:26:62)
#11     _startIsolate (dart:isolate-patch/isolate_patch.dart:237)
#12     _startMainIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:192)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:130)


#0      AnalysisContextImpl.recordResolveDartLibraryTaskResults (package:analyzer/src/generated/engine.dart:2115:11)
#1      AnalysisContextImpl_AnalysisTaskResultRecorder.visitResolveDartLibraryTask (package:analyzer/src/generated/engine.dart:5304:133)
#2      ResolveDartLibraryTask.accept (package:analyzer/src/generated/engine.dart:14327:77)
#3      AnalysisTask.perform (package:analyzer/src/generated/engine.dart:6732:18)
#4      AnalysisContextImpl._cacheDartResolutionData (package:analyzer/src/generated/engine.dart:2414:86)
#5      AnalysisContextImpl._getDartResolutionData (package:analyzer/src/generated/engine.dart:3046:41)
#6      AnalysisContextImpl._getDartResolutionData2 (package:analyzer/src/generated/engine.dart:3077:36)
#7      AnalysisContextImpl.computeLibraryElement (package:analyzer/src/generated/engine.dart:1192:81)
#8      DartDoc.parseLibraries.<anonymous closure> (package:dartdoc/dartdoc.dart:90:63)
#9      List.forEach (dart:core-patch/growable_array.dart:254)
#10     DartDoc.parseLibraries (package:dartdoc/dartdoc.dart:86:18)
#11     DartDoc.generateDocs (package:dartdoc/dartdoc.dart:42:31)
#12     main (file:///Users/sethladd/Code/dartdoc/bin/dartdoc.dart:26:62)
#13     _startIsolate (dart:isolate-patch/isolate_patch.dart:237)
#14     _startMainIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:192)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:130)

```

**Comment by sethladd** [comment]
If we mandate --dart-sdk, which I assume is the problem here, should we include an error message if you don't specify the SDK?

**Comment by sethladd** [comment]
FWIW, --dart-sdk doesn't show up in --help:

```
sethladd@sethladd-macbookair ~/Code/dartdoc (coverage)$ dart bin/dartdoc.dart --help
    --exclude    a comma-separated list of library names to ignore
    --url        the url where the docs will be hosted (used to generate the sitemap)
-h, --help       show command help
Usage: dartdoc [OPTIONS]
```

**Comment by devoncarew** [comment]
FYI, there's a utility method in grinder which does a reasonably good job of locating the sdk. It's a bit more sophisticated than the dartdoc's `_getSdkDir`. Happy to patch in a reference to it.

**Comment by keertip** [comment]
Followed your steps. Can reproduce the problem with

dart-uuid keertip$ dart ~/src/dartdoc/bin/dartdoc.dart

But this works fine for me

dart-uuid keertip$ ~/ide/eclipse382/dart-sdk/bin/dart
~/src/dartdoc/bin/dartdoc.dart










On Mon, Jan 5, 2015 at 5:45 PM, Devon Carew <notifications@github.com>
wrote:

> FYI, there's a utility method in grinder which does a reasonably good job
> of locating the sdk. It's a bit more sophisticated than the dartdoc's
> _getSdkDir. Happy to patch in a reference to it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/dartdoc/issues/42#issuecomment-68814165>.
>



-- 
Keerti

**Comment by keertip** [comment]
Thanks Devon, will take a look at the utility method.

@Seth, there is no option currently for passing in the sdk location.

On Mon, Jan 5, 2015 at 6:34 PM, Keerti Parthasarathy <keertip@google.com>
wrote:

> Followed your steps. Can reproduce the problem with
>
> dart-uuid keertip$ dart ~/src/dartdoc/bin/dartdoc.dart
>
> But this works fine for me
>
> dart-uuid keertip$ ~/ide/eclipse382/dart-sdk/bin/dart
> ~/src/dartdoc/bin/dartdoc.dart
>
>
>
>
>
>
>
>
>
>
> On Mon, Jan 5, 2015 at 5:45 PM, Devon Carew <notifications@github.com>
> wrote:
>
>> FYI, there's a utility method in grinder which does a reasonably good job
>> of locating the sdk. It's a bit more sophisticated than the dartdoc's
>> _getSdkDir. Happy to patch in a reference to it.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/dart-lang/dartdoc/issues/42#issuecomment-68814165>.
>>
>
>
>
> --
> Keerti
>



-- 
Keerti

**Comment by joelrich** [comment]
I am having the same problem in another project when I run ```pub serve``` (Pub 1.8.3). Is there anything I can do about it?

**Comment by sethladd** [comment]
Hi,

Is this an issue with pub serve or dartdoc?

**Comment by joelrich** [comment]
@sethladd with pub serve, but the first 5 frames of the stack frame are exactly the same which is why I hope that a similar workaround/fix could solve my problem too. I can of course also open a separate issue if you prefer. Here the stacktrace:

```
Unable to resolve asset ID for "dart:core"
Build error:
Transform Factory on vdom_benchmark|web/index.dart threw error: <rethrow>
Caused by Could not resolve dart:core
#0      AnalysisTask._safelyPerform (package:analyzer/src/generated/engine.dart:6762)
#1      AnalysisTask.perform (package:analyzer/src/generated/engine.dart:6727)
#2      AnalysisContextImpl._cacheDartResolutionData (package:analyzer/src/generated/engine.dart:2414)
#3      AnalysisContextImpl._getDartResolutionData (package:analyzer/src/generated/engine.dart:3046)
#4      AnalysisContextImpl._getDartResolutionData2 (package:analyzer/src/generated/engine.dart:3077)
#5      AnalysisContextImpl.computeLibraryElement (package:analyzer/src/generated/engine.dart:1192)
#6      ResolverImpl._performResolve.<anonymous closure>.<anonymous closure> (package:code_transformers/src/resolver_impl.dart:158)
#7      MappedListIterable.elementAt (dart:_internal/iterable.dart:417)
#8      ListIterable.toList (dart:_internal/iterable.dart:219)
#9      ResolverImpl._performResolve.<anonymous closure> (package:code_transformers/src/resolver_impl.dart:159)
#10     _RootZone.runUnary (dart:async/zone.dart:1155)
#11     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:484)
#12     _Future._propagateToListeners (dart:async/future_impl.dart:567)
#13     _Future._completeWithValue (dart:async/future_impl.dart:358)
#14     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:412)
#15     _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#16     _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:84)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:131)
```

**Comment by sethladd** [comment]
Hm, sorry about that. Could you file this as a bug on dartbug.com/new ? Thanks!

**Comment by joelrich** [comment]
@sethladd I have created the following issue: https://code.google.com/p/dart/issues/detail?id=22099

**Comment by sethladd** [comment]
@joelrich thanks!
