### ISSUE TITLE
Unable to tell what version dartdoc is

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#43]
```
sethladd@sethladd-macbookair ~/Code/dartdoc (coverage)$ dart bin/dartdoc.dart --version
Unhandled exception:
FormatException: Could not find an option named "version".
#0      Parser.validate (package:args/src/parser.dart:251:21)
#1      Parser.parseLongOption (package:args/src/parser.dart:240:15)
#2      Parser.parse (package:args/src/parser.dart:77:26)
#3      ArgParser.parse (package:args/src/arg_parser.dart:113:62)
#4      main (file:///Users/sethladd/Code/dartdoc/bin/dartdoc.dart:16:29)
#5      _startIsolate (dart:isolate-patch/isolate_patch.dart:237)
#6      _startMainIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:192)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:130)
```

**Comment by ricowind** [comment]
I guess this is a dub of:
https://code.google.com/p/dart/issues/detail?id=16718

**Comment by sethladd** [comment]
Thanks @ricowind, same type of issue.
