### ISSUE TITLE
Uncaught Error: Invalid argument(s): package:dartdoc/templates/index.html does not exist,

### ISSUE THREAD

**Issue by rayk** [dart-lang/dartdoc#462]
Hi Seth

Life appear to change as soon as I installed polymer???

Anyhow when I run dartdoc, which by the way is looking impressive... I get the following...

```bash
Rays-iMac:goapp rayk$ pub run dartdoc
Generating Dart API docs into docs
parsing /Users/rayk/code/goapp/lib/go_app.dart...
parsing /Users/rayk/code/goapp/lib/core/go_clock/go_clock.dart...
parsing /Users/rayk/code/goapp/lib/core/go_context/go_context.dart...
parsing /Users/rayk/code/goapp/lib/core/go_key/go_key.dart...
parsing /Users/rayk/code/goapp/lib/core/go_logger/go_logger.dart...
parsing /Users/rayk/code/goapp/lib/core/go_tools/word_dictionary_en.dart...
parsing /Users/rayk/code/goapp/lib/core/go_tools/word_parser.dart...

Parsed 7 libraries in 5.0 seconds.

Unhandled exception:
Uncaught Error: Invalid argument(s): package:dartdoc/templates/index.html does not exist, tried /Users/rayk/code/goapp/.pub/bin/dartdoc/packages/dartdoc/templates/index.html
Stack Trace:
#0      _readFile.<_readFile_async_body> (package:dartdoc/resource_loader.dart:115)
#1      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#2      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#3      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#4      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:886)
#1      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#2      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)
Rays-iMac:goapp rayk$ 
```
I have confirmed the `package:dartdoc/templates/index.html` does exist. But it is not in my `/Users/rayk/code/goapp/.pub/bin/dartdoc/packages/dartdoc/templates/index.html` , there is only  a snapshot file. 

``` bash

/Users/rayk/code/goapp/.pub/bin/dartdoc
Rays-iMac:dartdoc rayk$ ls -a
.                       ..                      dartdoc.dart.snapshot
Rays-iMac:dartdoc rayk$ 
```

Any pointers or ideas???

Thanks in Advance Ray...

**Comment by keertip** [comment]
@rayk,

How can I reproduce the issue? Against what package are you running dartdoc?

**Comment by rayk** [comment]
I will share the repo with you...

**Comment by keertip** [comment]
I am not able to reproduce the issue. Here's what I did

`pub global activate dartdoc`
The version of `dartdoc` is 0.0.1+10
`cd goapp`
`pub global run dartdoc`

The docs were generated into the `docs` folder, no exceptions.

**Comment by sethladd** [comment]
Try running dartdoc without `pub run` or `pub global run`. Just run `dartdoc` on your command-line

**Comment by rayk** [comment]
Thanks... Seth that worked... perfect.....

**Comment by sethladd** [comment]
We should be more explicit that we don't support running via `pub run` (due to too many inconsistencies)
