### ISSUE TITLE
null object does not have a getter 'name'

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#50]
To repro:

git clone git@github.com:google/quiver-dart.git
cd quiver-dart
dart ../dartdoc/bin/dartdoc.dart

output:

```
sethladd@sethladd-macbookair ~/Code/quiver-dart (master)$ dart ../dartdoc/bin/dartdoc.dart 
parsing /Users/sethladd/Code/quiver-dart/lib/async.dart...
parsing /Users/sethladd/Code/quiver-dart/lib/cache.dart...
parsing /Users/sethladd/Code/quiver-dart/lib/check.dart...
parsing /Users/sethladd/Code/quiver-dart/lib/collection.dart...
parsing /Users/sethladd/Code/quiver-dart/lib/core.dart...
parsing /Users/sethladd/Code/quiver-dart/lib/io.dart...
parsing /Users/sethladd/Code/quiver-dart/lib/iterables.dart...
parsing /Users/sethladd/Code/quiver-dart/lib/mirrors.dart...
parsing /Users/sethladd/Code/quiver-dart/lib/pattern.dart...
parsing /Users/sethladd/Code/quiver-dart/lib/streams.dart...
parsing /Users/sethladd/Code/quiver-dart/lib/strings.dart...
parsing /Users/sethladd/Code/quiver-dart/lib/time.dart...
parsing /Users/sethladd/Code/quiver-dart/lib/testing/async.dart...
parsing /Users/sethladd/Code/quiver-dart/lib/testing/runtime.dart...
parsing /Users/sethladd/Code/quiver-dart/lib/testing/time.dart...
generating docs/quiver_package.html
generating docs/quiver.async.html
Unhandled exception:
The null object does not have a getter 'name'.

NoSuchMethodError: method not found: 'name'
Receiver: null
Arguments: []
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#1      HtmlGeneratorHelper.createLinkedTypeName (package:dartdoc/src/generator.dart:536:30)
#2      HtmlGeneratorHelper.createLinkedTypeName (package:dartdoc/src/generator.dart:549:41)
#3      HtmlGeneratorHelper.createLinkedReturnTypeName (package:dartdoc/src/generator.dart:565:34)
#4      Typedef.createLinkedSummary (package:dartdoc/src/model.dart:405:51)
#5      HtmlGenerator.createToc (package:dartdoc/src/generator.dart:198:65)
#6      HtmlGenerator.generateLibrary (package:dartdoc/src/generator.dart:163:14)
#7      HtmlGenerator.generate.<anonymous closure> (package:dartdoc/src/generator.dart:41:55)
#8      List.forEach (dart:core-patch/growable_array.dart:254)
#9      HtmlGenerator.generate (package:dartdoc/src/generator.dart:41:30)
#10     DartDoc.generateDocs (package:dartdoc/dartdoc.dart:67:23)
#11     main (file:///Users/sethladd/Code/dartdoc/bin/dartdoc.dart:31:21)
#12     _startIsolate (dart:isolate-patch/isolate_patch.dart:237)
#13     _startMainIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:192)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:130)
```

**Comment by sethladd** [comment]
I think @keertip fixed this?

**Comment by sethladd** [comment]
Now it's fixed :)
