### ISSUE TITLE
Build failing on Windows

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#549]
Just saw this from our CI system:

```
Build started
git clone -q --branch=testing-branch git://github.com/dart-lang/dartdoc.git C:\projects\dartdoc
git checkout -qf 4a36081e07700278592d4092facb9f6e1ee01c9a
Running Install scripts
choco install -y dart-sdk -version 1.10.0
Chocolatey (v0.9.8.33) is installing 'dart-sdk' and dependencies. By installing you accept the license for 'dart-sdk' and each dependency you are installing. 
  
dart-sdk v1.10.0 
PATH environment variable does not have C:\tools\dart-sdk\bin in it. Adding... 
PATH environment variable does not have C:\Users\appveyor\AppData\Roaming\Pub\Cache\bin in it. Adding... 
Downloading dart-sdk 64 bit
  from 'https://storage.googleapis.com/dart-archive/channels/stable/release/45396/sdk/dartsdk-windows-x64-release.zip' 
Extracting C:\Users\appveyor\AppData\Local\Temp\chocolatey\dart-sdk\dart-sdkInstall.zip to C:\tools... 
C:\tools 
dart-sdk has finished successfully! The chocolatey gods have answered your request! 
Finished installing 'dart-sdk' and dependencies - if errors not shown in console, none detected. Check log for errors if unsure. 
set PATH=%PATH%;C:\tools\dart-sdk\bin
set PATH=%PATH%;%APPDATA%\Pub\Cache\bin
pub get
Resolving dependencies... 
Downloading analyzer 0.25.0+1... 
Downloading args 0.13.1... 
Downloading cli_util 0.0.1+2... 
Downloading den_api 0.1.0... 
Downloading grinder 0.7.1+3...
Downloading html 0.12.1+1...
Downloading http 0.11.2... 
Downloading intl 0.12.4...
Downloading librato 0.0.3...
Downloading logging 0.11.1...
Downloading markdown 0.7.1+2... 
Downloading mustache4dart 1.0.10...
Downloading path 1.3.5...
Downloading pub_cache 0.0.1+2...
Downloading quiver 0.21.3+1... 
Downloading unittest 0.11.6+1...
Downloading yaml 2.1.2... 
Downloading watcher 0.9.5...
Downloading which 0.1.3... 
Downloading contrast 0.1.1...
Downloading github 2.2.2...
Downloading pub_package_data 0.0.1...
Downloading pub_semver 1.2.1... 
Downloading source_span 1.1.2...
Downloading ansicolor 0.0.9...
Downloading glob 1.0.4...
Downloading http_server 0.9.5+1... 
Downloading unscripted 0.6.1+1...
Downloading webkit_inspection_protocol 0.0.1+1...
Downloading csslib 0.12.0+1... 
Downloading utf 0.9.0+2... 
Downloading http_parser 0.0.2+6...
Downloading stack_trace 1.3.2...
Downloading petitparser 1.4.3...
Downloading crypto 0.9.0... 
Downloading matcher 0.12.0+1... 
Downloading collection 1.1.1...
Downloading string_scanner 0.1.3+1...
Downloading when 0.2.0... 
Downloading xml 2.3.2...
Downloading barback 0.15.2+4...
Downloading mime 0.9.3...
Downloading mockable_filesystem 0.0.3... 
Downloading supports_color 0.1.1...
Downloading pool 1.0.2...
Got dependencies! 
Precompiling dependencies...
Loading source assets...
Precompiled intl. 
Precompiling executables... 
Loading source assets... 
Precompiled intl:extract_to_arb. 
Precompiled grinder:init.
Precompiled grinder:grinder.
Precompiled intl:generate_from_arb. 
pub run grinder buildbot
grinder running [analyze] [test] [test-dartdoc] [buildbot]
 
[analyze]
  dartanalyzer.bat --fatal-warnings bin/dartdoc.dart lib/dartdoc.dart test/all.dart
  Analyzing [bin/dartdoc.dart, lib/dartdoc.dart, test/all.dart]...
  No issues found
  No issues found
  No issues found
 
[test]
  dart.exe --checked test/all.dart
 
[test-dartdoc]
  running dartdoc
  dart.exe bin/dartdoc.dart --output C:\Users\appveyor\AppData\Local\Temp\doc\api
  Generating documentation for 'dartdoc' into C:\Users\appveyor\AppData\Local\Temp\doc\api\.
  
  parsing /C:/projects/dartdoc/lib/dartdoc.dart...
  parsing /C:/projects/dartdoc/lib/generator.dart...
  parsing /C:/projects/dartdoc/lib/markdown_processor.dart...
  parsing /C:/projects/dartdoc/lib/resources.g.dart...
  parsing /C:/projects/dartdoc/lib/resource_loader.dart...
  Parsed 0 files in 0.8 seconds.
  
  generating C:\Users\appveyor\AppData\Local\Temp\doc\api\index.html
  Documented 0 libraries in 2.0 seconds.
  
  Success! Open file://C:\Users\appveyor\AppData\Local\Temp\doc\api/index.html
 
GrinderException: docs not generated
#0      GrinderContext.fail (package:grinder/grinder.dart:148:5)
#1      fail (package:grinder/grinder.dart:103:38)
#2      testDartdoc (file:///C:/projects/dartdoc/tool/grind.dart:80:32)  failed: docs not generated
 
Command exited with code 1
```

**Comment by keertip** [comment]
Looks like it is building on Windows! We have to change the test - use path separator there too.

**Comment by sethladd** [comment]
Good catch!

**Comment by sethladd** [comment]
How's the build on Windows?

**Comment by keertip** [comment]
@sethladd, it should be fixed now. The PR with the fix failed - due to pub not running, and I could not figure out how to trigger another build.

**Comment by devoncarew** [comment]
I triggered one. From looking through the appveyor settings briefly, I couldn't see how to add you to the project.

**Comment by devoncarew** [comment]
We have one more test failure on windows:

https://ci.appveyor.com/project/devoncarew/dartdoc/build/1.0.80

Once that is fixed, the build should go green :)

**Comment by sethladd** [comment]
Related: https://github.com/dart-lang/dartdoc/issues/532

**Comment by sethladd** [comment]
There's a very strange build failure on our Windows build.

```
FAIL: Docs as HTML reference to class from another library
    Expected: contains '<a href="ex/Apple_class.html">Apple</a>'
      Actual: '<p>A super class, with many powers. Link to Apple from another library.</p>'
  
    package:unittest/src/simple_configuration.dart 128:34  SimpleConfiguration.onExpectFailure

```

Not sure why that would be specific for Windows...

**Comment by sethladd** [comment]
Bumping to P0 so we can get our builds clean. :)

**Comment by keertip** [comment]
Looked at this yesterday - spent close to an hour debugging. Found where the failure occurs, but not why. It fails when dartdoc is trying to find the library for class `Apple`. This is done by using the analyzer element model and figuring out if the `Apple` element is present to the namespace of any of the libraries in the package. The weird thing is that this fails only on Windows - works on the mac and linux.

**Comment by sethladd** [comment]
Thanks for checking into it. I wonder if we can reduce this down. So weird.

On Friday, June 12, 2015, Keerti Parthasarathy <notifications@github.com>
wrote:

> Looked at this yesterday - spent close to an hour debugging. Found where
> the failure occurs, but not why. It fails when dartdoc is trying to find
> the library for class Apple. This is done by using the analyzer element
> model and figuring out if the Apple element is present to the namespace
> of any of the libraries in the package. The weird thing is that this fails
> only on Windows - works on the mac and linux.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/dartdoc/issues/549#issuecomment-111523926>.
>


-- 
Sent from my Motorola Startac

**Comment by keertip** [comment]
We can not run this test for now on windows, and add to note to loop back to it. That way the bots would be green and useful.

**Comment by sethladd** [comment]
> We can not run this test for now on windows, and add to note to loop back
> to it. That way the bots would be green and useful.
>

Do we know if the test failure signals a real issue on Windows?

**Comment by sethladd** [comment]
See also https://github.com/dart-lang/dartdoc/issues/587

**Comment by sethladd** [comment]
I put in a trim() to unify line endings across Windows and Mac.

https://github.com/dart-lang/dartdoc/pull/952
