### ISSUE TITLE
NPE when generating docs

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#595]
To repro: `dart tool/doc_packages.dart bwu_utils_dev`.

```
NoSuchMethodError: method not found: 'split'
Receiver: null
Arguments: ["/"]
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      HtmlGeneratorInstance.generateClass (package:dartdoc/src/html_generator.dart:283:36)
#3      HtmlGeneratorInstance.generate.<generate_async_body>.<anonymous closure>.<anonymous closure> (package:dartdoc/src/html_generator.dart:141:9)
#4      List.forEach (dart:core-patch/growable_array.dart:234)
#5      HtmlGeneratorInstance.generate.<generate_async_body>.<anonymous closure> (package:dartdoc/src/html_generator.dart:140:22)
#6      List.forEach (dart:core-patch/growable_array.dart:234)
#7      HtmlGeneratorInstance.generate.<generate_async_body> (package:dartdoc/src/html_generator.dart:137:23)
```

See also https://github.com/dart-lang/dartdoc/pull/594/files#diff-b33dc7f777bad2309ac40d590d4a83c1R282

**Comment by devoncarew** [comment]
verified!

**Comment by keertip** [comment]
Thanks!
