### ISSUE TITLE
windows: test_template.dart fails depending on git configuration

### ISSUE THREAD

**Issue by guillermooo** [dart-lang/dartdoc#614]
On Windows, some tests fail with `git config core.autocrlf true`.

To get test to run without failing, you have to do this (maybe more steps in other configs) to remove carriage returns.

```
git config core.autocrlf false
git rm *
git reset --hard
```

Example of failures:

```
dartdoc $ dart .\test\template_test.dart
00:00 +0: template with sitemap render
00:00 +0 -1: template with sitemap render
  Expected: '<?xml version="1.0" encoding="UTF-8"?>\n'
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
    '  <url>\n'
    '    <loc>/somefile.html</loc>\n'
    '  </url>\n'
    '</urlset>\n'
    ''
    Actual: '<?xml version="1.0" encoding="UTF-8"?>\r\n'
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\r\n'
    '  <url>\r\n'
    '    <loc>/somefile.html</loc>\r\n'
    '  </url>\r\n'
    '</urlset>\r\n'
    ''
     Which: is different.
  Expected: ... "UTF-8"?>\n<urlset x ...
    Actual: ... "UTF-8"?>\r\n<urlset ...
                          ^
   Differ at offset 39

  package:test                  expect
  test\template_test.dart 28:9  main.<fn>.<fn>.<fn>

00:00 +0 -1: template with sitemap substitute multiple links
00:00 +0 -2: template with sitemap substitute multiple links
  Expected: '<?xml version="1.0" encoding="UTF-8"?>\n'
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
    '  <url>\n'
    '    <loc>/somefile.html</loc>\n'
    '  </url>\n'
    '  <url>\n'
    '    <loc>/asecondfile.html</loc>\n'
    '  </url>\n'
    '</urlset>\n'
    ''
    Actual: '<?xml version="1.0" encoding="UTF-8"?>\r\n'
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\r\n'
    '  <url>\r\n'
    '    <loc>/somefile.html</loc>\r\n'
    '  </url>\r\n'
    '  <url>\r\n'
    '    <loc>/asecondfile.html</loc>\r\n'
    '  </url>\r\n'
    '</urlset>\r\n'
    ''
     Which: is different.
  Expected: ... "UTF-8"?>\n<urlset x ...
    Actual: ... "UTF-8"?>\r\n<urlset ...
                          ^
   Differ at offset 39

  package:test                  expect
  test\template_test.dart 39:9  main.<fn>.<fn>.<fn>

00:00 +0 -2: template with sitemap url and file name
00:00 +0 -3: template with sitemap url and file name
  Expected: '<?xml version="1.0" encoding="UTF-8"?>\n'
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
    '  <url>\n'
    '    <loc>http://mydoc.com/somefile.html</loc>\n'
    '  </url>\n'
    '</urlset>\n'
    ''
    Actual: '<?xml version="1.0" encoding="UTF-8"?>\r\n'
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\r\n'
    '  <url>\r\n'
    '    <loc>http://mydoc.com/somefile.html</loc>\r\n'
    '  </url>\r\n'
    '</urlset>\r\n'
    ''
     Which: is different.
  Expected: ... "UTF-8"?>\n<urlset x ...
    Actual: ... "UTF-8"?>\r\n<urlset ...
                          ^
   Differ at offset 39

  package:test                  expect
  test\template_test.dart 55:9  main.<fn>.<fn>.<fn>

00:00 +0 -3: Some tests failed.

Unhandled exception:
Uncaught Error: Dummy exception to set exit code.
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:886)
#1      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#2      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:392)
#5      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:411)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:142)
```

If I've understood it correctly, the problem seems to be that Dart normalizes line endings in literal strings, but not when reading from a file (the failing tests read from a file). Example of normalization:

```
main() {
  var s = """
    huh?
    """;

  var t = """
    huh?\r
    """;

  print(s.contains('\r')); // false
  print(t.contains('\r')); // true
}
```

File contents:

![crlf](https://cloud.githubusercontent.com/assets/684948/8391067/95c7eaf2-1cb2-11e5-87a0-815cafcd221e.png)

I couldn't find anything about newline chars normalization in the docs, but I haven't checked the spec, so my understanding may be wrong.

**Comment by guillermooo** [comment]
So it appears that `0x000D` bytes are stripped from literal strings in .dart files in all cases, but `File.readAsString[Async]()` doesn't do that. This feels inconsistent, since the file's content is being treated as a literal string.

**Comment by sethladd** [comment]
Thanks for the report!

**Comment by sethladd** [comment]
We now trim() all HTML docs, which fix the tests to work on both Mac and Windows. going to close now, but please comment if there's still an issue.
