### ISSUE TITLE
Running dartdoc in empty directory fails with misleading error

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#740]
```
~/tmp/docs $ dart /Users/sethladd/Code/dartdoc/bin/dartdoc.dart
Unhandled exception:
Uncaught Error: Invalid argument(s)
Stack Trace:
#0      _StringBase._interpolate (dart:core-patch/string_patch.dart:828)
#1      main.<main_async_body> (file:///Users/sethladd/Code/dartdoc/bin/dartdoc.dart:108:60)
#2      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#3      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#4      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#5      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:895)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

```

**Comment by sethladd** [comment]
I'll fix this.

**Comment by sethladd** [comment]
Now we say this:

```
~/tmp/docs $ dart /Users/sethladd/Code/dartdoc/bin/dartdoc.dart
Unable to generate documentation.
* No pubspec.yaml found
```

**Comment by sethladd** [comment]
Addressed by https://github.com/dart-lang/dartdoc/pull/741
